### ISSUE TITLE
useHead with scripts, how set html attribute to ="true"

### ISSUE THREAD

**Issue by yvess** [unjs/unhead#103]
### Environment

 "dependencies": {
    "@vueuse/core": "^9.10.0",
    "debounce": "^1.2.1",
    "graphql": "^16.5.0",
    "graphql-request": "^4.3.0",
    "lru-cache": "^7.14.0",
    "nodemailer": "^6.8.0"
  },
  "devDependencies": {
    "@types/node": "^18.11.18",
    "@typescript-eslint/parser": "^5.33.0",
    "@vue/cli-plugin-eslint": "^5.0.6",
    "@vue/eslint-config-typescript": "^11.0.0",
    "autoprefixer": "^10.4.8",
    "nuxt": "^3.2.0",
    "typescript": "^4.7.4",
    "vue-tsc": "^1.0.24"
  }

### Reproduction

in nuxConfig.ts in a nuxt 3 project

 app: {
    head: {
      script: [{
      hid: 'test',
      src: 'https://test.com/test.js',
      'data-test': 'true',
    }],
  }
}

### Describe the bug

I need to add a custom data script tag in vue3 which has a html attribute set to 'true', this should render as **="true"** but renders as **=""**. 

I can see that this is done intentionally https://github.com/unjs/unhead/blob/main/packages/unhead/src/utils/normalise.ts function normaliseProps line 57.

This behaviour changed from nuxt 3 rc11 to rc12 in a useHead refactor. Before that it worked as expected.

**Comment by harlan-zw** [comment]
Hey @yvess, thanks for the issue :)

It was changed to this as the HTML spec says that they are equivalent, so we opt for the one that is less verbose.

If you're trying to test if these props are truthy client side you should check they exist and aren't false. Is there a specific package that has this logic or is this your code?

I'm open to changing the logic for data attributes. I'll keep the issue open to gather feedback.

**Comment by yvess** [comment]
I anybody else has the issue, we currently use a workaround with a NitroPlugin with `html.head.push()` to add html to the header

**Comment by harlan-zw** [comment]
@yvess I've fixed this in this PR.

I'll likely introduce this in a 1.1 release soon.

**Comment by yvess** [comment]
@harlan-zw thanks!
