### ISSUE TITLE
Double spaces in class list result in console error.

### ISSUE THREAD

**Issue by vanling** [unjs/unhead#104]
### Environment

Node 18
Nuxt 3.2.2 with Nitro 2.2.2

### Reproduction

app.vue

```
<template>
  <Html :lang="'nl'">
    <Body
      :class="[
        'relative min-h-screen  antialiased' // double space between min-h-screen and antialiased
      ]"
    >
      <NuxtLayout>
        <NuxtPage />
      </NuxtLayout>
    </Body>
  </Html>
  ```

### Describe the bug

When adding 2 spaces between 2 classnames in classlist, some console errors popup.

Not an big issue, should not have double spaces in the first place ;) but this might cause some confusion for other people and lead to unnecessary bug reports here or in Nuxt

### Logs

```sh
uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.     at https://localhost:3000/_nuxt/node_modules/@unhead/dom/dist/index.mjs?v=6cfd573a:18:25
```
```

**Comment by harlan-zw** [comment]
Hey @vanling 

Thanks for the detailed issue and the PR attempt! It definitely fixed the issue so nice job. 

I thought I better fix the issue at the normalization phase though, that way the SSR and DOM rendering has the same conditions. PR here: https://github.com/unjs/unhead/pull/108

Will close your PR. Fix will likely be available in v1.1 which will be released soon.
