### ISSUE TITLE
Cyrillic characters in the title

### ISSUE THREAD

**Issue by evoart-studio** [unjs/unhead#106]
### Environment

Last release Nuxt

### Reproduction

Just add cyrillic characters in the title

### Describe the bug
After the last update, Cyrillic characters in the title are converted to html code, for example `&#1055;&#1091;&#1084;&#1087;&#1091;&#1088;&#1091;&#1088;&#1091;&#1084;`

**Comment by harlan-zw** [comment]
This was to resolve XSS issues in the `<title>`, afaik these encoded characters won't cause issues with rendering the title or SEO.

I can look at less aggressive encoding, but is it causing issues?

**Comment by niklaswolf** [comment]
So yeah, it causes issues in nuxt-og-image as can be seen from the linked issue above ;)

**Comment by evoart-studio** [comment]
if we're talking only about client-side rendering, then there's no problem.  but if we need ssr it can be displayed very badly on seo

**Comment by harlan-zw** [comment]
I will work on a fix for this. This shouldn't be an SEO issue though. HTML entities are valid and will be parsed

**Comment by harlan-zw** [comment]
Have pushed up a fix, will only encode the following characters:

```
 Encode the following characters:
   & --> &amp;
   < --> &lt;
   > --> &gt;
   " --> &quot;
   ' --> &#x27;
   / --> &#x2F;
```

Will likely land in v1.1, which will be released soon.

Thanks for the issue!

**Comment by kostia7alania** [comment]
When I pass a number to the title, the page breaks !

This breaks the error page in production! You fixed this bug in vain with regexp without type checking.
This dangerous bug can lead to errors in the production of sites on Nuxt!
This will reduce the credibility of Nuxt! This is discrediting the reputation of Nuxt!

<img width="779" alt="image" src="https://user-images.githubusercontent.com/18175496/223087307-f7d59595-e241-4204-8eb1-2c7d1449c098.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/18175496/223086989-1ad44226-3d06-4c36-9498-11a723b06a15.png">

[https://t.me/nuxtjs_ru/213128/227097](https://vk.com/away.php?utf=1&to=https%3A%2F%2Ft.me%2Fnuxtjs_ru%2F213128%2F227097)
