### ISSUE TITLE
Nuxt useServerSeoMeta issue with app.head config

### ISSUE THREAD

**Issue by VladStepanov** [unjs/unhead#116]
### Environment

No need

### Reproduction

No need

### Describe the bug

As i understand from the types of `useSeoMeta`, there is no way to provide deduplication key for tags. Is it planned as enhancement?

**Comment by harlan-zw** [comment]
Hi @VladStepanov 

All meta props should dedupe themselves, is there a specific meta you're having issue with?

**Comment by VladStepanov** [comment]
@harlan-zw Yes, either i don't understand something, or deduplication is not working
I provide a reproduction https://stackblitz.com/edit/nuxt-starter-fch4mx?file=nuxt.config.ts,app.vue
Steps to reproduce:
1. Open repro
2. With devtools inspect `meta[name=description]` in head.
3. `meta[name=description]` should be `useServerSeoMeta description`
Instead we got `nuxt.config.ts description`

**Comment by harlan-zw** [comment]
> @harlan-zw Yes, either i don't understand something, or deduplication is not working I provide a reproduction https://stackblitz.com/edit/nuxt-starter-fch4mx?file=nuxt.config.ts,app.vue Steps to reproduce:
> 
> 1. Open repro
> 2. With devtools inspect `meta[name=description]` in head.
> 3. `meta[name=description]` should be `useServerSeoMeta description`
>    Instead we got `nuxt.config.ts description`

Ah ye so this is actually a bug with Nuxt. It's because of the nuxt.config app.head is mounted for both client and server side,
whereas you're only mounting your useServerSeoMeta on the server.

This will be fixed in Nuxt soon, in the meantime replace `useServerSeoMeta` with `useSeoMeta` and it should solve it.
