### ISSUE TITLE
page breaks if pass a number to the title

### ISSUE THREAD

**Issue by kostia7alania** [unjs/unhead#122]
### Environment

Last release Nuxt

### Reproduction

Just add number characters in the title

### Describe the bug

When I pass a number to the title, the page breaks !

This breaks the error page in production! You fixed this bug in vain with regexp without type checking.
This dangerous bug can lead to errors in the production of sites on Nuxt!
This will reduce the credibility of Nuxt! This is discrediting the reputation of Nuxt!

<img width="779" alt="image" src="https://user-images.githubusercontent.com/18175496/223087307-f7d59595-e241-4204-8eb1-2c7d1449c098.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/18175496/223086989-1ad44226-3d06-4c36-9498-11a723b06a15.png">

[https://t.me/nuxtjs_ru/213128/227097](https://vk.com/away.php?utf=1&to=https%3A%2F%2Ft.me%2Fnuxtjs_ru%2F213128%2F227097)

### Additional context

relates 
https://github.com/unjs/unhead/issues/106

**Comment by kostia7alania** [comment]
hot to make a Merge request to the repo? 

https://github.com/unjs/unhead/pull/123/files

**Comment by harlan-zw** [comment]
While this package should be able to handle it, the types clearly define that it should be a string value. 

![image](https://user-images.githubusercontent.com/5326365/223114190-97901632-ce07-4d0b-ab62-fd8f93168723.png)

I've pushed up a fix  in v1.1.17

If _you_ have lost credibility with Nuxt, that's okay, we don't need rude people using it.
