### ISSUE TITLE
Vue 2 support docs: vueuse in import

### ISSUE THREAD

**Issue by obulat** [unjs/unhead#124]
### Environment

All

### Reproduction

Go to https://unhead.harlanzw.com/integrations/vue/setup#vue-2 and read the sample code.

### Describe the bug

The setup says to import from `@vueuse/head`. Is that a typo, or does unhead not support Vue 2?
<img width="631" alt="Screenshot 2023-03-08 at 6 43 25 AM" src="https://user-images.githubusercontent.com/15233243/223614321-805384c0-8699-4094-bd0c-b6010ffac069.png">

**Comment by harlan-zw** [comment]
Hey @obulat 

Thanks for the issue. This is indeed a typo, @unhead/vue exports the same plugin though
