### ISSUE TITLE
nuxt plugin hydration on SSR

### ISSUE THREAD

**Issue by c-schwan** [unjs/unhead#128]
### Environment

Operating System: Darwin
Node Version: v19.5.0
Nuxt Version: 3.3.1

### Reproduction

The title on titleTemplate on app mount is is null, after the page finished its update the title, so the title is jumping each refresh.

nuxtApp.hooks.hook('page:start', () => { pauseDOMUpdates = true })-> title is null
nuxtApp.hooks.hook('page:finish', unpauseDom)-> title  not null
nuxtApp.hooks.hook('app:mounted', unpauseDom) -> title is null

### Describe the bug

hi @harlan-zw,

i opened an issue with dom replace when titleTemplate is set.

[#19680](https://github.com/nuxt/nuxt/issues/19680#issue-1623697348)

Can we just remove the app:mounded hook? Because its breaks the ssr client hydration.

**Comment by harlan-zw** [comment]
Hi @c-schwan, thanks for the issue

Would you be able to provide a reproduction on StackBlitz? It's a little unclear how you managed this

**Comment by brtinney** [comment]
Re: https://github.com/nuxt/nuxt/issues/19680

Looking back at https://github.com/nuxt/nuxt/issues/14438, the [repro you had there](https://stackblitz.com/edit/nuxt-starter-bdn1o1?file=pages/index.vue) still has the issue in the latest version of Nuxt: https://stackblitz.com/edit/nuxt-starter-gz3qh8?file=package.json

**Comment by c-schwan** [comment]
> That hook is needed to avoid the same issue when navigating between pages

but the hook page:finish calls already the unpauseDom between client side navigation pages

after comment out those line (nuxtApp.hooks.hook('app:mounted', unpauseDom)) everthing works fine in ssr + client hydration and client navigation (client only)

**Comment by harlan-zw** [comment]
Thanks guys, PR is open https://github.com/nuxt/nuxt/pull/19740
