### ISSUE TITLE
Duplicated script tags after hydration when using the nonce attribute

### ISSUE THREAD

**Issue by paulnta** [unjs/unhead#136]
### Environment

- Node v18
- Vue v3.2.47

### Reproduction

https://stackblitz.com/edit/unhead-duplicated-script-nonce?file=app.vue

### Describe the bug

When using `useHead` with SSR, adding the `nonce` attribute on scripts causes the script to be injected twice in the page head.

```js
useHead({
  script: [
    {
      nonce: 'nonce-8IBTHwOdqNKAWeKl7plt8g==',
      innerHTML: "console.log('will log twice')",
    },
  ],
});
```

Adding the `key`, `vmid` or `hid` attribute does not prevent duplication because of this issue https://github.com/unjs/unhead/issues/135. 

So currently my workaround is to use the server-only mode (`useHead(input, { mode: 'server' })`) in combination with the `key` attribute.

### Additional context

For security reasons, the `nonce` attribute is [hidden by the browser](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce#accessing_nonces_and_nonce_hiding). So `$el.getAttribute('nonce')` returns an empty string, which breaks the [Tag Deduping](https://unhead.harlanzw.com/guide/guides/handling-duplicates) logic.

**Comment by harlan-zw** [comment]
This appears to be fixed as we don't allow duplicate tag content in one of the more recent updates.
