### ISSUE TITLE
Console logs "Cannot read properties of undefined (reading 'startsWith')" when using the composition API

### ISSUE THREAD

**Issue by maartenkools** [unjs/unhead#140]
### Environment

- @vueuse/head 1.1.23
- unhead 1.1.23
- @unhead/addons 1.1.25
- Vue 3.2.47
- Vite 4.0.0

### Reproduction

Add the following to the component:

```vue
<script lang="ts" setup>
import { useHead } from "@unhead/vue";

useHead({
    title: "My title"
});

// ...
</script>
```

### Describe the bug

When I add the composable, the page breaks with a script error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')`

![image](https://user-images.githubusercontent.com/9009075/228820384-e3ef5f33-744e-4a21-ac00-8f7d538479b9.png)

**Comment by maartenkools** [comment]
There are multiple imports that are undefined in the @unhead/vue/dist/shared/vue.3c82dacb.mjs file:

- getCurrentInstance
- onBeforeUnmount
- version

**Comment by harlan-zw** [comment]
Hey @maartenkools, thanks for the issue.

I believe this would be an issue with your build setup most likely. The `version` constant should be exported from Vue.

Are you able to provide a reproduction through Stackblitz?

**Comment by maartenkools** [comment]
@harlan-zw Try this https://stackblitz.com/edit/vitejs-vite-1gfvkx, I managed to reproduce it with that

**Comment by harlan-zw** [comment]
> @harlan-zw Try this https://stackblitz.com/edit/vitejs-vite-1gfvkx, I managed to reproduce it with that

Amazing, thanks!

Not sure exactly what's going on but you can fix the issue with

```ts
export default defineConfig({
  optimizeDeps: {
    exclude: ['@vueuse/head'],
  },
  plugins: [vue(), VueI18nPlugin(), UnheadVite()],
  server: {
    port: 5173,
  },
});
```

See https://stackblitz.com/edit/vitejs-vite-umazgu?file=vite.config.ts,node_modules%2Fvite%2Fdist%2Fnode%2Findex.d.ts,src%2FApp.vue,package.json

I'll try dig into it further if I find some time

**Comment by maartenkools** [comment]
Thanks! I did manage to get it to work by importing `@vueuse/head`. Didn't have to exclude it from optimization (at least not in the project we're implementing this, perhaps in the Stackblitz snippet it's different). 

What I did notice, is that the `vue3-apexcharts` package seems part of the issue. If you remove the use of that, the problem is gone.
