### ISSUE TITLE
The `key` property does not replace an item with the same key, and in fact destroys elements that don't share the key

### ISSUE THREAD

**Issue by matthew-dean** [unjs/unhead#145]
### Environment

Node - v16
@unhead/vue - 1.1.25

### Reproduction

https://codesandbox.io/s/condescending-dewdney-me6dqx?file=/src/App.vue

### Describe the bug

I'm providing a list of Google font stylesheet links. Each one is assigned a key.

When a value changes, I'm calling `useHead` again and one of the values loads the entire font file (with an altered querystring variable), and continues to provide the same key.

In the reproduction, when you inspect the document, you can see the 3 link tags. However, when the state changes, even though there should continue to be 3 items, two of them disappear. Instead of the keys having _no_ effect, and de-duping, instead they have a _negative_ effect and destroy more than the keys should allow.

You can even see by logging the items that there are 3 keys each time, but only 3 links the first time.

**Comment by harlan-zw** [comment]
> 

Thanks! Just FYI you don't need to provide a `key` for canonical, it will already dedupe the tag accross pages. 

The bug is still valid for other keyd data and I'm working on a fix

**Comment by harlan-zw** [comment]
Thanks for the reproduction @matthew-dean 

This should now be fixed in v1.1.26, let me know if you have any issues with it :)

**Comment by thijs-justacodename** [comment]
Yes! This fixed the issues with canonical link deduplication too! Thanks!!! (Used yarn resolutions to update nuxt deps)
