### ISSUE TITLE
VueHeadMixin not working with vue 2.7.14 and options API

### ISSUE THREAD

**Issue by mass4441** [unjs/unhead#161]
### Environment

Environment
"@unhead/vue": "^1.1.27",
"vue":"2.7.14",
node 18.15.0

### Reproduction

Try to use the "head" key in your components with Options API and set a title. 

### Describe the bug

The document title is not updated. Looks like the key "Head" is not recognized. 

### Additional context

useHead instead work when using composition API with the same configuration.

**Comment by harlan-zw** [comment]
Hi, can you please provide a reproduction?

Vue 2 is working as far as I know, see the example here: https://github.com/unjs/unhead/tree/main/examples/vue-2

**Comment by harlan-zw** [comment]
Sorry, I took another look at this and you're right. It's fixed in 1.3.5
