### ISSUE TITLE
Title deduplication priority

### ISSUE THREAD

**Issue by 719media** [unjs/unhead#165]
### Describe the feature

Currently, it appears that unhead deduplicates tags based on "last fired" (most recent).

It would be helpful if there was an API to allow some level of prioritization to the deduplication of tags, such that when two duplicate meta tags inside of two separate useHead() methods are called, there is a way to indicate which one should take priority.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hey @719media, thanks for the issue.

Did you see the [Tag Sorting](https://unhead.harlanzw.com/guide/guides/sorting) documentation? Let me know if there's something missing there to achieve what you're trying to handle.

**Comment by 719media** [comment]
Thanks for the reply.
My issue isn't the SORTING of the tags, but the prioritization of deduplication.

My use case is that I have several nested components that set unique tag (say for example, the title tag), and I want the "most nested" to take priority. For example, imagine componentB is nested inside componentA.

```
// componentA
useHead({title: computed(() => { return someValue.value; })});
```
```
// componentB
useHead({title: computed(() => { return someOtherValue.value; })});
```

And after componentB setup is complete, something happens such that someValue changes as causes a re-render of componentA. Problem is, now the title from componentA will be the title of page, not the title of componentB as desired.

Obviously there are "workarounds", using global state values to make the componentA computed property more dependent, etc.

Something like:

```
// componentA
useHead({title: computed(() => { return someValue.value; }), priority: 8});
```
```
// componentB
useHead({title: computed(() => { return someOtherValue.value; }), priority: 1});
// priority: 1 indicates that, as long as this component is in use, then this title should be used instead of componentA's title
```

I realize the problem here is that the useHead is not "stateful" in that way, and more of a functional fire, so it probably isn't really an easy fix.

**Comment by 719media** [comment]
I also see that on the page https://unhead.harlanzw.com/integrations/vue/reactivity#best-practices

You recommend not using computed.

In my application, I am doing SPA and so the title/etc. is not always ready pending additional loads of dynamic information. I wonder if, instead of having useHead have computed property, it is better to restructure and have fetch responses "re-call" useHead... not exactly a 1:1 relationship, but just a different way of accomplishing things.

Seems like one of the problems with computed is that, if any of the "lower priority" properties re-render, it will cause issues for prioritizing the de-duplications.

**Comment by harlan-zw** [comment]
To clarify, sorting the tags is the step before deduplication. The deduping is based on the position of the tags.

The issue you have though is that only the new tag input allows you to provide a priority, the title does not. 

Ideally, you'd be able to do something like this

```ts
// a
useHead({
   title: {
      textContent: 'My title',
      tagPriority: 'critical'
   }
})

// b
useHead({
   title: 'new title'
})

// title will be a
```

Computer getters should be reactive, there is some magic around them.

**Comment by harlan-zw** [comment]
In v1.1.28, it's now possible to provide a tagPriority to the title and title template.

```ts
useHead({
   title: {
      textContent: 'My title',
      tagPriority: 'critical'
   }
})
```
