### ISSUE TITLE
Is there a way to disable sanitization

### ISSUE THREAD

**Issue by ariana-min** [unjs/unhead#168]
### Describe the feature

I'm trying to set an og:image that is generated by mapbox [Static Images API](https://docs.mapbox.com/playground/static/).
I'm adding GeoJSON layers that define color with a #RRGGBB notation. For that to work I need to escape that to %23RRGGBB.
It seems that the useUead (or useSeoMeta) are removing url encoded strings like the %23 during the sanitation step. Sanitation seem to happen in all places even though there is a useHeadSafe where I'd expect it to happen.

I have no way of disabling the sanitize step or otherwise workaround that issue. I'm using nuxt 3.

It would be great if you could consider an option to disable the sanitize step, or give me some pointer how to workaround that issue.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hey @ariana-min, thanks for the issue.

I wasn't able to replicate this. I tried with the following input:

```ts
  useHead({
      meta: [
        {
          property: 'og:image',
          content: 'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/geojson({"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[125.6,10.1]},"fillColor":"%23eeeeee","properties":{"name":"Dinagat Islands"}}]})/-122.3486,37.8169,9,0/300x200?access_token=YOUR_MAPBOX_ACCESS_TOKEN',
        }
      ]
    })
```

Which gave the output

```html
<meta property=\"og:image\" content=\"https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/geojson({&quot;type&quot;:&quot;FeatureCollection&quot;,&quot;features&quot;:[{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;Point&quot;,&quot;coordinates&quot;:[125.6,10.1]},&quot;fillColor&quot;:&quot;%23eeeeee&quot;,&quot;properties&quot;:{&quot;name&quot;:&quot;Dinagat Islands&quot;}}]})/-122.3486,37.8169,9,0/300x200?access_token=YOUR_MAPBOX_ACCESS_TOKEN\">
```

Which looks correct?

Are you able to provide some reproduction details
