### ISSUE TITLE
Escape html tags in doc comments?

### ISSUE THREAD

**Issue by brc-dd** [unjs/unhead#170]
Currently, there are comments like this:

```ts
  /**
   * The <meta> element represents metadata that cannot be expressed in other HTML elements, like <link> or <script>.
   *
   * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
   */
  meta?: Meta<E['meta']>[]
```

An issue with these is they won't render properly on hovering in VSCode as the html tags are not escaped:

<img width="699" alt="image" src="https://github.com/unjs/unhead/assets/40380293/0b6dc8f3-7d8b-4007-851e-eb5d38051fee">

\
A fix can be to change the comments to something like this:

```ts
  /**
   * The `<meta>` element represents metadata that cannot be expressed in other HTML elements, like `<link>` or `<script>`.
   *
   * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
   */
  meta?: Meta<E['meta']>[]
```

Rendered comment:

<img width="701" alt="image" src="https://github.com/unjs/unhead/assets/40380293/d0cd23cf-0844-47e8-a7e3-5a063286900f">

\
PS: there seems to be a typo here:

https://github.com/unjs/unhead/blob/e224e77e320420c8633b45ea98890c8fe9adc5b7/packages/schema/src/tags.ts#L18-L23

**Comment by harlan-zw** [comment]
Thanks, was not aware of that! Have pushed up a fix for this and for https://github.com/harlan-zw/zhead as well
