### ISSUE TITLE
useSeoMeta pulling in data from other pages - Nuxt3

### ISSUE THREAD

**Issue by nathansmedley** [unjs/unhead#178]
### Environment

"nuxt": "^3.6.5",

### Reproduction

https://voicenationdev.netlify.app/ - Page title will change from onload to something else after a few seconds then when you scroll to the footer it will change again.

### Describe the bug

Hello, 
I'm currently setting up a new site im just putting all the SEO meta data in for the pages however pages seem to be pulling through meta data from other pages,

If you go to this url: https://voicenationdev.netlify.app/

The useSeoMeta in the code is:
```
<script setup>
useSeoMeta({
  title: 'Answering Service - Virtual Receptionist - VoiceNation',
  description: 'Award-winning answering service to grow your business. Increase sales, capture leads, improve customer experience. Affordable plans.',
});
```

However which is what it shows when the page loads also shows that in the source, then it will change to "Plans Pricing" which is from this page: https://voicenationdev.netlify.app/plans-pricing/

And then the really strange page if you scroll to the bottom of the page it will change to "Privacy policy"

Has anyone come across this before or know what i've done wrong? this is my first time building anything in vue/nuxt

Thanks

**Comment by harlan-zw** [comment]
I think it might be an issue with your code, are you calling it within the `setup()` function?
