### ISSUE TITLE
using null to remove an existing head tag

### ISSUE THREAD

**Issue by 719media** [unjs/unhead#179]
### Describe the feature

When doing something like

```
meta: [{
  property: 'og:video',
  content: null,
}]
```

it actually creates
```
<meta property="og:video" content="null">
```

I was attempting to use `null` as a means of "unsetting" the meta property, but obviously it did not work. The same happens with `undefined`.

Not sure if this creates other problems of deduplication, etc., but it would be nice if this worked.

The specific use case is removing a meta tag that's defined in index.html outside of unhead.js... unhead will REPLACE existing head tags, but to remove?? not sure

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
This should actually be the behavior, will look at fixing it. Thanks!

**Comment by cbedwell-dev** [comment]
I agree, this would be a very helpful feature! I use hid's to override meta tags on each page, and when the values of these tags are null it creates an undefined tag, rather than ignoring them completely and defaulting to the tags at the global level.

**Comment by 719media** [comment]
It works according to one definition.
One example up for debate is if your raw html (before unhead) has a meta tag:
```
<html>
  <meta property="og:image" content="https://domain.com/image.jpg">
```

And unhead has a meta tag definition of
```
{
  property: 'og:image',
  content: null,
  tagPriority,
}
```

You could say that the null should remove the original og:image defined in html. In the case of current unhead logic, it's treating the null as more of a "fallback to whatever was in original html"

As such, there's not an "easy" way to remove original html meta tags from unhead. The workaround is to remove them "manually" upon unhead initialization.

**Comment by harlan-zw** [comment]
Good point, have moved to this issue for discussion https://github.com/unjs/unhead/issues/232
