### ISSUE TITLE
Extend tagPositions for the head tag

### ISSUE THREAD

**Issue by aeadedoyin** [unjs/unhead#181]
### Describe the feature

It will be helpful to be able to position links in the head too and not just the body.

Today we have Body:
```ts
bodyOpen
bodyClose
```

We should also have Head:
```ts
headOpen
headClose
```

The use case for this is in prioritising(headClose) and/or deprioritising(headOpen) certain CSS links, especially local links in the static(public) folder for my project (Nuxt)

Sample:
```ts
  app: {
    head: {
      htmlAttrs: {
        lang: 'en'
      },
      link: [
        { tagPosition: 'headClose', href: 'css/normalize.css' },
        { tagPosition: 'headClose', href: 'css/webflow.css' },
        { tagPosition: 'headClose', href: 'css/_main.css' }
      ],
      script: headScripts() as any
    },
    pageTransition: { name: 'page', mode: 'out-in' }
  },
```

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hi @aeadedoyin, sorry for the delay.

You can control the head position by using the `tagPosition` property, see https://unhead.harlanzw.com/guide/guides/sorting

Let me know if you have any questions about that.

**Comment by harlan-zw** [comment]
Yes, you should use `transformHtmlTemplate()` if you'd like to re-order tags inserted from Vite (or elsewhere).

See https://unhead.unjs.io/docs/vue/head/guides/get-started/installation#_3-setup-server-side-rendering
