### ISSUE TITLE
Vite + Vue 2.7 + unhead doesn't seem to update the page `title` tag

### ISSUE THREAD

**Issue by Qobrarod** [unjs/unhead#191]
### Environment

Here the `package.json` file :

```json
{
  "name": "ui",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "build": "vite",
    "dev": "vite"
  },
  "dependencies": {
    "@unhead/vue": "^1.3.4",
    "@vitejs/plugin-vue2": "^2.2.0",
    "vue": "^2.7.14"
  },
  "devDependencies": {
    "@unhead/addons": "^1.3.4",
    "@vitejs/plugin-vue": "^4.2.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5",
    "vue-tsc": "^1.8.5"
  }
}
```

### Reproduction

I tried to create the smallest reproducible environment on a `codesandbox` here :  https://codesandbox.io/p/sandbox/friendly-sunset-xw82mw?file=/src/App.vue:6,16

## What happens

The `head` option in the `script` tag of the `App.vue` file doesn't seem to update the `title` of the `head` tag of the HTML page when loaded

## What I expect 

The title of the browser tab should be changed (and in the debug tool we should be able to see those changes reflected in the `title` tag inside the `head` tag)

### Additional context

I don't know if using Vite + Vue 2.7.14 is a know issue, or if I am just miss-using `unhead`
I tried to follow as best as I can those tutorial
- https://unhead.harlanzw.com/integrations/vue/setup
- https://unhead.harlanzw.com/guide/getting-started/vite-plugin

**Comment by Qobrarod** [comment]
Vue 3 + Vite + unhead is working fine : https://codesandbox.io/s/serene-morning-f2hhyh?file=/src/App.vue

**Comment by harlan-zw** [comment]
Hi @Qobrarod, thank you for the detailed issue.

You'll need to use the VueHeadMixin to use the options API. However, there was a bug in the mixin plugin for Vue 2 where it wasn't working so you'll need to use the latest version (1.3.5)

See https://unhead.harlanzw.com/integrations/vue/options-api

Let me know if you have any issues with that

**Comment by Qobrarod** [comment]
Indeed it is working fine now !
I had tried with the mixin but didn't know I was not using the latest version
Thank you !!

**Comment by harlan-zw** [comment]
> Indeed it is working fine now ! I had tried with the mixin but didn't know I was not using the latest version Thank you !!

I only pushed this version when I posted this comment, so I'd be surprised if you did :stuck_out_tongue: 

Thanks for the update
