### ISSUE TITLE
Re-Export `resolveUnrefHeadInput`

### ISSUE THREAD

**Issue by razorness** [unjs/unhead#192]
### Describe the feature

Is ther any reason `@unhead/vue` stopped exporting the utility method `resolveUnrefHeadInput`? I found it handy when developing your own plugin. 

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hey @razorness, these was mainly to decrease the bundle size of the package and make treeshaking easier.

I'm open to re-exporting it though, would you mind sharing how you're using it?
