### ISSUE TITLE
fix: set property without empty string as value

### ISSUE THREAD

**Issue by dargmuesli** [unjs/unhead#199]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      app, devtools, modules
- Runtime Modules:  @nuxtjs/html-validator@1.5.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-b2yprs?file=package.json

### Describe the bug

Starting with Nuxt 3.7 the html validator plugin reports that `<link rel="modulepreload" as="script" crossorigin="" href="...">` `crossorigin` and two other similar occurences now have an empty value (`=""`) set when it should not have this value: https://html-validate.org/rules/attribute-empty-style.html
For Nuxt 3.6.5 the validator did not find this.

**New:** Actually, I would propose [what you mentioned too](https://github.com/nuxt/nuxt/issues/22825#issuecomment-1694217818): set the value to `anonymous` instead of nothing :raised_hands:

### Additional context

Continuation from https://github.com/nuxt/nuxt/issues/22825

**Comment by dargmuesli** [comment]
Could it be that the attribute again has an empty value?

**Comment by dargmuesli** [comment]
E.g. in [this stackblitz](https://stackblitz.com/edit/github-3gjye4-smy5xt?file=package.json) I have `<script type="module" src="/_nuxt/@vite/client" crossorigin=""></script>`

**Comment by dargmuesli** [comment]
@harlan-zw given the minimal reproduction from my previous comment, could we reopen this issue or does the issue have a different source this time?

**Comment by harlan-zw** [comment]
I think that reproduction was using an old locked Unhead version, see https://stackblitz.com/edit/github-3gjye4-smy5xt?file=package.json

**Comment by dargmuesli** [comment]
I've updated all dependencies and the lockfile and still have `crossorigin=""`: https://stackblitz.com/edit/github-3gjye4-smy5xt?file=package.json

Or am I misunderstanding something?

**Comment by harlan-zw** [comment]
![image](https://github.com/unjs/unhead/assets/5326365/dc338ebc-fcfb-42dd-92c5-f9b9bae28cf4) I can't replicate with that link?

Keep in mind I only have control over the SSR response behavior for this, if you set an attribute using the client-side `document` API, it will add an empty string. This is why the SSR behavior originally did it as well.

**Comment by dargmuesli** [comment]
Ohh, in Firefox's developer console those show as `=""`, in Chrome they show without!

How did you get the frame's page source to show? I get `Access-Control-Allow-Origin` errors:

![image](https://github.com/unjs/unhead/assets/4778485/aab13a3f-fb06-4909-88a8-26d623d6abd4)

**Comment by harlan-zw** [comment]
Ahh... no idea, seems to just work in Chrome :P 

You do need to open in a seperate window first

**Comment by dargmuesli** [comment]
Ok, you're right, the Stackblitz I sent is in fact correct. Firefox's developer tools made it look different.
I get some related errors in a project of mine though, I'll investigate further now that I know how to do that window linking! Thank you very much for sharing that :heart:
