### ISSUE TITLE
Provide a default stack blitz template for bug/issue reporting

### ISSUE THREAD

**Issue by 719media** [unjs/unhead#212]
### Describe the feature

Provide a default stack blitz template for bug/issue reporting. Easier for first time reporters, and could also make maintainers life easier by having bugs reported extending from the same "template".

An example can be see in the default template for bootstrap issue bug report creation:
https://github.com/twbs/bootstrap/issues/new?assignees=-&labels=bug&projects=&template=bug_report.yml&title=Provide+a+general+summary+of+the+issue
```
Include links [reduced test case](https://css-tricks.com/reduced-test-cases/) links or suggested fixes using CodePen ([v4 template](https://codepen.io/team/bootstrap/pen/yLabNQL) or [v5 template](https://codepen.io/team/bootstrap/pen/qBamdLj)).
```
You can start with one I created from vite default, I'm sure you can simplify it. (https://stackblitz.com/edit/vitejs-vite-umdqwq) Figure it would be best created by project owner as it should be controlled by repository owner.

Just a suggestion. Maybe this isn't as helpful to you as it is for me.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
I think this is a great idea, thank you!

Have used your template and added it to the README and the doc, will add more as they come up.
