### ISSUE TITLE
Vue 2 renders SSR output only on first request

### ISSUE THREAD

**Issue by vetruvet** [unjs/unhead#216]
### Environment

vue 2.7.14
@unhead/ssr 1.5.4
@unhead/vue 1.5.4
Node 18.12.0

### Reproduction

https://github.com/vetruvet/unhead-vue2-first-request-bug (instructions to install/build/run in README of the repo).

### Describe the bug

Upon starting the server, only the first visit to the page will render tags. Subsequent visits will render empty tags.
The issue does not exist using a comparable setup under vue 3.

**Comment by vetruvet** [comment]
Found what seems to be causing it: when calling `Vue.use(Vue2ProvideUnheadPlugin, head)` after the first time, vue will see the plugin as already installed, and will not install it again with the new head instance.

Also found a workaround: register the plugin on an extended vue rather than right on imported vue
e.g.

```
//...
const LocalVue = Vue.extend({});

const head = createHead();
LocalVue.use(head); // though this seems unnecessary since head.install only does something under vue 3
LocalVue.use(Vue2ProvideUnheadPlugin, head);

const app = new LocalVue(...);
// ...
```

**Comment by harlan-zw** [comment]
Thanks for the issue @vetruvet. Looks like you have come across the correct problem.

With 1.6.0 I've pushed up a subpath export for vue2 that introduces a simpler API, the updated code would look like. Have updated the docs accordingly. 

```ts
import { UnheadPlugin } from '@unhead/vue/vue2';
import { renderSSRHead } from '@unhead/ssr';
import { createHead } from '@unhead/vue'

// ...

  const head = createHead();
  Vue.mixin(UnheadPlugin(head));
  const renderer = createRenderer();
  const app = new Vue({
    render: h => h(root),
  });
```

Let me know if there's anything I missed with it, will close for now.

**Comment by vetruvet** [comment]
There is another problem with the `Vue.extend` workaround now in 1.6.2: anything registered on that extended object only applies to the root component, which means the options API functionality of the mixin does not work for any other components (the `provide` part is fine since it really only needs to be on the root anyway.

Previously in 1.5.4 the workaround was ok since I would register `Vue.mixin(VueHeadMixin)` on the global object once so all components get that mixin, and then do `LocalVue.use(Vue2ProvideUnheadPlugin, head)` with the extended object (and only root gets this but that's fine for `provide`)

**Comment by vetruvet** [comment]
@harlan-zw I think that the changes 1dfe189e would still result in the same behavior as I described [here](https://github.com/unjs/unhead/issues/216#issuecomment-1711902384). I raised #227 to make the vue 2 plugin act more like how pinia does it (get the unhead instance from the component options instead of passing it in explicitly). Let me know what you think of that approach.
