### ISSUE TITLE
tagToString in @unhead/ssr escapes JSON with no effect

### ISSUE THREAD

**Issue by vetruvet** [unjs/unhead#218]
### Environment

@unhead/ssr 1.5.4

### Reproduction

https://github.com/vetruvet/unhead-vue2-first-request-bug

### Describe the bug

https://github.com/unjs/unhead/blob/main/packages/ssr/src/util/tagToString.ts#L53 runs after `content` is set so the escaping has no effect

### Additional context

Fix PR incoming

**Comment by harlan-zw** [comment]
Available in 1.5.5 :)
