### ISSUE TITLE
JSON escaping causes duplicate tag on client-side hydration

### ISSUE THREAD

**Issue by vetruvet** [unjs/unhead#223]
### Environment

@unhead/vue 1.6.2
@unhead/ssr 1.6.2
vue 2.7.14
Node 18.12

### Reproduction

https://github.com/vetruvet/unhead-vue2-first-request-bug/tree/with-client (note the `with-client` branch, reusing repo from older issue)

### Describe the bug

When creating a JSON script tag, `<` gets escaped to `\u003C` server-side.
Client-side seems to be unaware of that escaping, so it creates a duplicate tag client side.

To reproduce:

1. Clone reproduction repo (`with-client` branch) and install , build, and run as in readme
2. Go to `localhost:9999`
3. Inspect page

Observe the server-side-escaped JSON script tag alongside the client-side (not escaped) JSON script tag.

### Additional context

In case this helps at all to arrive at a fix... in prior versions of unhead (1.0.x) where this JSON escaping was not present, I built an escaping plugin using the `tag:normalize` hook that would do `<` and `&` escaping on both client and server side, and that seemed to work fine.

**Comment by danielroe** [comment]
cc: @harlan-zw
