### ISSUE TITLE
<Head> template tag in Vue 3

### ISSUE THREAD

**Issue by rezelute** [unjs/unhead#224]
### Describe the feature

I was hopeful that I would be able to use the `<Head>` tag in Vue 3 template soon, could you please give me with an idea if this feature has already been released (but not yet documented) or provide an approx ETA on when this might be implemented?

You used to have a page that was talking about this integration with Vue however this page is not found now: https://unhead.unjs.io/integrations/vue/vueuse-head

Thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hi, if you'd like to use the components you can use the https://github.com/vueuse/head repo. The only difference is that it exports the components

**Comment by rezelute** [comment]
But i thought that library was being sunsetted? We were using Vite-SSG which was using that library however it is now using unjs/unhead in the latest version. This means that I now need to go across the whole project to change:
```
<Head>
      <title>my title</title>
      <meta name="description" :content="my content" />
   </Head>
```
To script setup syntax.

**Comment by harlan-zw** [comment]
I'll try fix this for you, give me a couple of hours.

**Comment by rezelute** [comment]
oh awesome, thank you for looking into it! 🙏

**Comment by harlan-zw** [comment]
I need to do some proper documentation but you can do this in 1.7.0

```vue
<script setup>
import { Head } from '@unhead/vue/components'
</script>
<template>
  <Head>
    <title>Hello World</title>
  </Head>
</template>
```

**Comment by rezelute** [comment]
This is awesome, thank you for this quick update 🚀
