### ISSUE TITLE
useHead script innerHTML property is getting set as src instead

### ISSUE THREAD

**Issue by TechAkayy** [unjs/unhead#228]
### Environment

@unhead/vue: 1.7.0
nodejs: v18.12.1

### Reproduction

Doesn't work with @unhead/vue: 1.7.0 - https://github.com/pinegrow/pg-nuxt-vuetify-tailwindcss
Worked fine previously with @unhead/vue: 1.3.4 - https://github.com/TechAkayy/happy-paws-with-nuxt-tailwindcss

Please refer to component `components/MetaTags.vue` and below screenshot. 

### Describe the bug

Script is getting added as `src` instead of `innerHTML`. I tried using `textContent` as well, and that throws an error as well. 

![image](https://github.com/unjs/unhead/assets/73772701/94e33e8a-4b08-46e8-ba76-0a7bf1ace420)

**Comment by harlan-zw** [comment]
Thanks for the detailed issue. This should be fixed in [v1.7.3](https://github.com/unjs/unhead/commit/2709d5b9e886e3e555fb47a513c0d07346e5db44) with https://github.com/unjs/unhead/commit/ce89ceb860e3c1addb9cbf3b1ee9167b982e2ce0
