### ISSUE TITLE
Use SingleFamilyResidence schema

### ISSUE THREAD

**Issue by argenisleon** [unjs/unhead#237]
### Describe the feature

Is there a way to create a not-implemented schema like https://schema.org/SingleFamilyResidence?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hi @argenisleon, thanks for the issue. I think there was some confusion around using custom nodes in the docs beforehand. I've updated it and added some examples https://unhead.unjs.io/schema-org/recipes/custom-nodes

The scope of official nodes is only applicable to ones that provide Rich Results.

Let me know if that isn't clear.
