### ISSUE TITLE
@unhead/vue imcompatible with vite-ssg

### ISSUE THREAD

**Issue by ansidev** [unjs/unhead#239]
### Environment

Node 16+, pnpm v8

### Reproduction

https://github.com/ansidev/blog/pull/630

### Describe the bug

@unhead/vue imcompatible with vite-ssg

### Logs

https://app.netlify.com/sites/ansidev/deploys/65026d1e559ee30008f22f80

**Comment by harlan-zw** [comment]
Need to investigate further but this is likely an issue with needing to update your vite-ssg dependency
