### ISSUE TITLE
Vue component documentation question or bug

### ISSUE THREAD

**Issue by rezelute** [unjs/unhead#241]
### Environment

Node.js

### Reproduction

Try to use:  `import { Head } from '@unhead/vue/components'` in the project as documented.

### Describe the bug

![image](https://github.com/unjs/unhead/assets/13378850/b0035d9a-e17a-4faa-aa9b-135afd2611e6)

I get a TS error when importing Head which is: `import { Head } from "@unhead/vue/components";`
Cannot find module '@unhead/vue/components' or its corresponding type declarations.ts(2307)

### Additional context
Seems to work fine if i add the path manually to TS config:
```
"paths": {
         "@/*": ["./src/*"],
         "@unhead/vue/*": ["node_modules/@unhead/vue/dist/*"]
      },
```

_No response_

**Comment by a0s** [comment]
The project looks abandoned, documentation is not kept up to date, no mention of "@unhead/vue". Should archaeological excavations in issues be part of the workflow?

**Comment by asvishnyakov** [comment]
Any updates on this?

**Comment by harlan-zw** [comment]
I believe this comes down to your Node and TypeScript versions as well as your tsconfig.json.

I've pushed up a workaround using `typesVersions` that may help, if you try out v1.8.3.

Otherwise please provide the versions you're using and config.

**Comment by harlan-zw** [comment]
Closing off as I haven't heard anything, feel free to bump if it's not fixed.

**Comment by asvishnyakov** [comment]
@harlan-zw I can confirm it's working. Thank you!
