### ISSUE TITLE
fix: schema-org regression since `1.8.0-beta.5`

### ISSUE THREAD

**Issue by dargmuesli** [unjs/unhead#262]
### Environment

- @nuxtseo/module v2.0.0-beta.39
- unhead v1.8.0-beta.5

### Reproduction

https://github.com/dargmuesli/vio/actions/runs/6699750370/job/18204497093?pr=112#step:7:1273

### Describe the bug

Raising this issue quickly, can work on a full reproduction if necessary.

Updating to anything since v`1.8.0-beta.5` (could be `.4` or `.3` instead, they're not on npm.com) makes my regression test fail with this diff:

![image](https://github.com/unjs/unhead/assets/4778485/f881aed6-8632-4757-8401-71c98bd28b26)

### Additional context

I'm defining schema-org like this:

```ts
const siteConfig = useSiteConfig()

useSchemaOrg([
  defineWebSite({
    description: siteConfig.description,
  }),
])
```

Notice that in the diff the `WebSite` part stays the same while the `WebPage` part changes.

**Comment by dargmuesli** [comment]
Hmm, there might be something else going on here. On static build, no `og.png`s are generated as well even when pinning unhead to `1.8.0-beta.2`. I'm a bit confused, but I guess my dependency pinning doesn't make incompatibilities less likely...

**Comment by harlan-zw** [comment]
Thanks, investigating this

**Comment by harlan-zw** [comment]
@dargmuesli is this fixed in latest? :thinking:

**Comment by dargmuesli** [comment]
I think so. I'll be able to tell for sure once https://github.com/harlan-zw/nuxt-seo-kit/issues/112 is resolved.

**Comment by dargmuesli** [comment]
Indeed it is! Thank you very much @harlan-zw :heart:
