### ISSUE TITLE
Request to Add "JobPosting". (schema.org)

### ISSUE THREAD

**Issue by dankozz1t** [unjs/unhead#264]
### Describe the feature

I have been exploring the [unhead](https://github.com/unjs/unhead) repository and the associated documentation available at [https://unhead.unjs.io/schema-org/schema/](https://unhead.unjs.io/schema-org/schema/). While going through the "Nodes" section, I noticed that the type "JobPosting" is not listed as one of the supported types.

It plays a significant role in enhancing the search appearance and relevance of web content. Detailed information about the "JobPosting" type can be found on the following resources:

- Google Developers - Structured Data for Job Posting:
https://developers.google.com/search/docs/appearance/structured-data/job-posting

- Schema.org - JobPosting:
https://schema.org/JobPosting

I may be missing some information and I would greatly appreciate your guidance on how to proceed with adding 'JobPosting'.

Sincerely,
Alex

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by alessioforti** [comment]
I'm in your same situation.
The JobPosting is missing in the docs, but I found it is actually implemented in the package:

[https://github.com/unjs/unhead/blob/main/packages/schema-org/src/nodes/JobPosting/index.ts](https://github.com/unjs/unhead/blob/main/packages/schema-org/src/nodes/JobPosting/index.ts)

So, we can actually use:
```javascript
useSchemaOrg([
  defineJobPosting({
    datePosted: ...,
    description: ...,
    hiringOrganization: ...,
    jobLocation: ...,
    title: ...,
    baseSalary: ...,
    jobLocationType: ...,
    directApply: true
  })
])
``` 

We can pass custom fields too, like:
```javascript
validThrough:  ...,
``` 
I'm fiddling with it just now

**Comment by dankozz1t** [comment]
@alessioforti Thank you very much for helping me! 
I would not have thought to look for what is not written in the documentation :)

**Comment by alessioforti** [comment]
@dankozz1t  you're welcome! I think I was just lucky :)

Here is a full example which seems to work. 
I used a composable just for convenience and to handle some logic.
Please note that `employmentType`, `baseSalary`, `jobLocation`, `applicantLocationRequirements` and `jobLocationType` should be marked appropriately as noted in the Google Developer page you linked to too.

Hoping this will be useful for others to come, still I think it should be included in the docs!
( maybe you could re-open the issue :D )

```javascript
// /composables/useJobPostingMeta.js

export const useJobPostingMeta = (job) => {

  const jobPosting = {
    datePosted: new Date(job.publish_date).toUTCString(),
    validThrough: new Date(job.expiry_date).toUTCString(),
    title: job.title,
    description: job.description,
    hiringOrganization: {
      name: job.company.name,
      sameAs: job.company.url,
      url: job.company.url,
      // TODO: 'logo': job.company.logoURL
    },
    employmentType: () => {
      switch (job.employment_type) {
        case 'full-time': return 'FULL_TIME'
        case 'part-time': return 'PART_TIME'
        case 'intern': return 'INTERN'
        case 'temporary': return 'TEMPORARY'
        case 'contractor': return 'CONTRACTOR'
        default: return 'OTHER'
      }
    },
    directApply: true
  }

  // Handle income (show range if supplied)
  if (job.income_to > 0) {
    jobPosting.baseSalary = {
      currency: 'USD',
      value: {
        minValue: job.income_from,
        maxValue: job.income_to,
        unitText: 'YEAR'
      }
    }
  } else {
    jobPosting.baseSalary = {
      currency: 'USD',
      value: {
        value: job.income_from,
        unitText: 'YEAR'
      }
    }
  }

  // Show correct markup based on job location
  // https://developers.google.com/search/docs/appearance/structured-data/job-posting#remote-jobs
  if (job.location == 'remote') {
    jobPosting.applicantLocationRequirements = {
      '@type': 'Country',
      name: 'USA'
    }
    jobPosting.jobLocationType = 'TELECOMMUTE'
  }

  if (job.location == 'hybrid') {
    jobPosting.applicantLocationRequirements = {
      '@type': 'Country',
      name: 'USA'
    }
    jobPosting.jobLocationType = 'TELECOMMUTE'
    jobPosting.jobLocation = {
      address: {
        streetAddress: "1600 Amphitheatre Pkwy",
        addressLocality: "Mountain View",
        addressRegion: "CA",
        postalCode: "94043",
        addressCountry: "US"
      }
    }
  }

  if (job.location == 'on-site') {
    jobPosting.jobLocation = {
      address: {
        streetAddress: "1600 Amphitheatre Pkwy",
        addressLocality: "Mountain View",
        addressRegion: "CA",
        postalCode: "94043",
        addressCountry: "US"
      }
    }
  }


  useSchemaOrg([
    defineJobPosting(jobPosting)
  ])
}
```

**Comment by dankozz1t** [comment]
@alessioforti Thank you once again
I'll leave this open for them to notice! :)

**Comment by harlan-zw** [comment]
Docs are now added https://unhead.unjs.io/schema-org/schema/job-posting, thanks for the issue.

**Comment by alessioforti** [comment]
Thanks @harlan-zw! Great!
