### ISSUE TITLE
Docs Nav Is Broken On Mobile

### ISSUE THREAD

**Issue by harlan-zw** [unjs/unhead#279]
### Environment

-

### Reproduction

![image](https://github.com/unjs/unhead/assets/5326365/82dfe79a-d0b9-4e32-96b5-057af732de16)

### Describe the bug

Menu isn't available / blank screen

**Comment by Young-Einstein10** [comment]
@harlan-zw This looks like it's been fixed.

<img width="335" alt="Screenshot 2023-12-08 at 07 59 27" src="https://github.com/unjs/unhead/assets/45533201/c2a8adb8-2d24-4a96-bb23-74e39dd57717">
