### ISSUE TITLE
Schema for Podcasts

### ISSUE THREAD

**Issue by andreasdiehl** [unjs/unhead#288]
### Describe the feature

Are there any plans to implement a Schema also for podcast episodes?
https://unhead.unjs.io/schema-org/getting-started/setup

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Sure, will built it when I have some time otherwise PRs welcome :)

**Comment by harlan-zw** [comment]
On further research, Google does not officially support Schema.org for podcasts so I don't plan on adding it to Unhead.
