### ISSUE TITLE
JSON like escaping for title instead of HTML like

### ISSUE THREAD

**Issue by holtwick** [unjs/unhead#292]
### Environment

node 20, mac m1, vite5, vue, vite-ssg

### Reproduction

```
useHead({
  title: `Tag "${tag}"`,
})
```

Produces `Tag \"tag\"`

### Describe the bug

Quotes in title get escaped to `\"`. Should be `&quot;`.

**Comment by harlan-zw** [comment]
As far as I could tell this is no longer the case, can you make a reproduction if you are able to still replicate it.

**Comment by MickL** [comment]
Having the same issue. Can we reopen please @harlan-zw ?

```
useSeoMeta({
    title: 'Test "123"',
  });
```

Becomes: `Test \"123\"`

I am on latest Nuxt `3.12.3` which uses latest unhead `1.9.16`

**Comment by jfern01** [comment]
Can confirm this is still happening. This particularly sucks for us because most of our meta titles contain double quotes.

**Comment by harlan-zw** [comment]
I've tried to replicate this without any success. If anyone can provide a reproduction using the latest it would be helpful.

**Comment by harlan-zw** [comment]
Thanks but I can't do anything with this, I need to be able to reproduce it locally to fix the issue.

**Comment by holtwick** [comment]
I can no longer reproduce the error either. IMO the bug is fixed. Thanks.

**Comment by MickL** [comment]
I am still having the same issue

**Comment by harlan-zw** [comment]
I'm happy to re-open once there's a reproduction available I can use to fix the issue, I can't reproduce it so I can't fix it.
