### ISSUE TITLE
`createHead` doesn't work in prod unless i call `.push({})` on it

### ISSUE THREAD

**Issue by huseeiin** [unjs/unhead#294]
### Environment

unhead: ^1.8.9
node: 20.10.0

### Reproduction

```tsx
import { render } from "preact";
import { Link } from "react-router-dom";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { createHead, useHead } from "unhead";

createHead();

function Home() {
	useHead({ title: "Home" });

	return (
		<main>
			<h1>Hello World</h1>
			<Link to="/about">About</Link>
		</main>
	);
}

function About() {
	useHead({ title: "About" });

	return (
		<main>
			<h1>About</h1>
			<Link to="/">Home</Link>
		</main>
	);
}

function App() {
	return (
		<BrowserRouter>
			<Routes>
				<Route index element={<Home />} />
				<Route path="/about" element={<About />} />
			</Routes>
		</BrowserRouter>
	);
}

const root = document.querySelector("#root");

if (root) render(<App />, root);
```

this works in dev perfectly. but in prod you have to do `createHead().push({})` for it to work again.

### Describe the bug

see `Reproduction`

**Comment by harlan-zw** [comment]
Hi @xxxhussein 

Thanks for the issue. Is it possible to make a StackBlitz reproduction? I don't know preact or how to set it up.

There's a Vue starter here that you may be able to start from https://stackblitz.com/edit/vitejs-vite-uijgqa?file=package.json

**Comment by hussseein** [comment]
> Hi @xxxhussein
> 
> Thanks for the issue. Is it possible to make a StackBlitz reproduction? I don't know preact or how to set it up.
> 
> There's a Vue starter here that you may be able to start from https://stackblitz.com/edit/vitejs-vite-uijgqa?file=package.json

i had this in both react and preact. you can start a project with either using `npm create vite`

**Comment by harlan-zw** [comment]
Happy to look into this but I need a reproduction on StackBlitz, will close for now.

**Comment by Kntt** [comment]
i have the same problem~
