### ISSUE TITLE
Schema.org Date Format Transformed Incorrectly

### ISSUE THREAD

**Issue by mrkclub2** [unjs/unhead#296]
Is it possible to add Timezone information to `datePublished`  or `dateModified` like `2011-12-03T10:15:30+01:00` ?

**Comment by harlan-zw** [comment]
Hi, I'm not sure I understand your issue. Would you provide some more detail?

Unhead does not do any transforms to dates

**Comment by harlan-zw** [comment]
Oh right, didn't realize you were talking about schema.org, this makes sense. Will look to get this fixed, thanks for the issue.

**Comment by harlan-zw** [comment]
I've updated it so it won't modify date/time inputs when the value provided is a valid ISO 8601 format available in 1.8.10
