### ISSUE TITLE
Custom key for UseSeoMetaInput

### ISSUE THREAD

**Issue by electrocnic** [unjs/unhead#298]
### Describe the feature

Tried to augment the `UseSeoMetaInput` type in typescript with my own custom meta tag, which I need because I use https://github.com/prerender/prerender

and it expects this meta value for 404 pages (or they would be prerendered) for my SPA vue app.

```ts
import 'unhead'

declare module 'unhead' {
	interface UseSeoMetaInput {
		'prerender-status-code'?: { content: string };
	}
}
```

However, it does not work and I did not find any "custom key" in unhead or zhead or a way to augment this correctly.

Want to use it like this:
```vue
<script setup lang="ts">
import { useSeoMeta } from 'unhead'
useSeoMeta({
	robots: 'noindex',
	'prerender-status-code': {
		content: '404'
	}
})
</script>
```
But I get:
```
error TS2353: Object literal may only specify known properties, and ''prerender-status-code'' does not exist in type 'UseSeoMetaInput'.
```

Would be nice if this specific type could either be added, or somebody told me how to augment it properly, or somebody told me how to add my custom type or allow to add a custom key. Thanks in advance!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
I think you'd have a much easier time if you just use `useHead`, `useSeoMeta` is just a convenience DX layer.

```ts
useHead({
  meta: [
    name: 'prerender-status-code',
    content: '404',
  ]
})
```

If you really want to augment the useSeoMeta types you should augment `MetaFlat`. Also there isn't any point having a content key, this is implied.

```ts
declare module 'unhead' {
	interface MetaFlat {
		'prerender-status-code'?: '404' | string
	}
}
```

**Comment by electrocnic** [comment]
Nice, this works perfectly fine!
Turns out I just did not know how to use this library properly ^^'

Thank you so much!
