### ISSUE TITLE
Resetting state after server-side rendering

### ISSUE THREAD

**Issue by lermontex** [unjs/unhead#300]
### Describe the feature

I'm using Vue 3.4 + Vite 5.0 to render the page server side:

head/index.js

```
import { createHead, createServerHead } from "@unhead/vue";

const head = import.meta.env.SSR ? createServerHead() : createHead();

export default head;
```

entry-server.js
```
// ...
import head from "@/head";

export async function render(req, manifest = null) {
  const app = createSSRApp({
    render: () => h(App),
  });
  
  app.use(head);
  
  const { headTags, bodyTags } = await renderSSRHead(head);
    
  return {
    headTags,
    bodyTags,
  };
}
```

I recently discovered that pages were showing tags that shouldn't be there. For example, after going to page “a”, where there is a “description” tag, I go to page “b”, for which the “description” tag is not set, but it is still displayed (there is a value from page “a”).

As far as I understand, the problem is that `createServerHead` is called once, then it is filled with values that were set on different pages.

Not entirely sure if this is the expected behavior. Is this how it should be?

Right now I'm not using imports, but calling `createServerHead` directly in the render function:

entry-server.js
```
// ...
export async function render(req, manifest = null) {
  const app = createSSRApp({
    render: () => h(App),
  });
  
  const head = createServerHead(); <<<--- this solves the problem
  
  app.use(head);
  
  const { headTags, bodyTags } = await renderSSRHead(head);
    
  return {
    headTags,
    bodyTags,
  };
}
```

In this case, the error does not occur. Is there a solution to reset the state of an imported head object?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
The head instance needs to be created with the app, you can't have a single instance of it otherwise you'll get tags leaking as you've experience.

**Comment by lermontex** [comment]
@harlan-zw, The thing is that in my use case I create and configure a "head" instance at one point in the application. This allows you to structure your application more flexibly.

It was actually a surprise to me that the object would not be recreated. If this is not an error, we can close this issue, but perhaps it is worth mentioning this in the documentation?

I found a similar use case for Apollo, their documentation states:

> It's important to create an entirely new instance of Apollo Client for each request. Otherwise, your response to a request might include sensitive cached query results from a previous request.

https://www.apollographql.com/docs/react/performance/server-side-rendering/#example
