### ISSUE TITLE
Open Graph meta-tags ignored in FB, X, Linkedin link/post

### ISSUE THREAD

**Issue by Dagge11** [unjs/unhead#303]
### Environment

Vue3/Vite/Nodejs + useSeoMeta() and useHead()

### Reproduction

```
useSeoMeta({
        title: rawMeta.value.vehicle_headl.substr(0, 46) + ' - mySite',
        description: 'tip motora ' + rawMeta.value.vehicle_engtype + ', godina ' + rawMeta.value.vehicle_age + ', kilometara ' + rawMeta.value.vehicle_km + ', snaga ' + rawMeta.value.vehicle_ccm + ' kW' + descr.value,
        ogDescription: 'tip motora ' + rawMeta.value.vehicle_engtype + ', godina ' + rawMeta.value.vehicle_age + ', kilometara ' + rawMeta.value.vehicle_km + ', snaga ' + rawMeta.value.vehicle_ccm + ' kW' + descr.value,
        ogTitle: rawMeta.value.vehicle_headl.substr(0, 46) + ' - mySite',
        ogUrl: 'https://www.mysite.com' +  route.fullPath,
        ogImage: 'https://www.mysite.com/images/' + rawMeta.value.image,
        ogImageWidth: '1200',
        ogImageHeight: '800',
        ogSite_name: 'mysite.com',
        ogImageType: 'image/png',
        ogTwitterImage: 'https://www.mysite.com/images/' + rawMeta.value.image,
        twitterCard: 'summary_large_image'
      })
```

### Describe the bug

Using Open Graps tags in head of each page via _useHead()_ or _useSeoMeta()_ displays _og:_ tags in Chrome Dev tools, but is ignored when posting page link inside FB, X or LinkedIn post. Those posts show only _og:_ data hardcoded in _index.html_ page, but not those on Vue rendered pages, inserted via _useSeoMeta()_.

The error shown on [FB Sharing Debugger](https://developers.facebook.com/tools/debug) is: _The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags._ Same on the [Linkedin Post Inspector](https://www.linkedin.com/post-inspector/inspect/) (X has abandoned such tool).

pls what can be done to display image, headline and description on every linked post in FB and other social networks. Thanks

**Comment by guijsbr** [comment]
I'm facing the same "problem" and from what I've researched this is not a bug, but an expected behavior in SPA's. It seems there's no simple solution and you need to prerender the website with a service like [https://prerender.io/](url).

**Comment by Dagge11** [comment]
@guijsbr prerender.is is not a solution because it doesn't work with Node.js and Express directly. They require SSR which is complicated and demanding on the server, or some kind of a middleman like paying Cloudflare CDN
