### ISSUE TITLE
LiveBlogPosting

### ISSUE THREAD

**Issue by djixadin** [unjs/unhead#306]
### Describe the feature

i looked through source code and the docs but i didnt found on how to use this particular schema. is it even implemented?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
You can just use an Article and provide the additional type:

```ts
defineArticle({
  '@type': ['LiveBlogPosting'],
  ...
})
```

You're always welcome to add a custom node as well, see https://unhead.unjs.io/schema-org/recipes/custom-nodes

**Comment by djixadin** [comment]
I see. The problem is that live blog posting and coverage start time arent supported and therefore wont be added to schema org.. ill take a look about custom nodes and see what i can do

**Comment by harlan-zw** [comment]
> I see. The problem is that live blog posting and coverage start time arent supported and therefore wont be added to schema org.. ill take a look about custom nodes and see what i can do

The nodes should support any arbitrary key, they just won't be typed

```ts
defineArticle({
  '@type': ['LiveBlogPosting'],
  coverageStartTime: '2022-10-20',
  ...
})
```

**Comment by djixadin** [comment]
i tried putting coverageStartTime like that and it doesn't appear in the html when inspecting. also i dont get types 
![image](https://github.com/unjs/unhead/assets/22941532/7eac83b7-8624-4eea-bb29-356787f3d403)

using nuxt seo v2 rc4

**Comment by harlan-zw** [comment]
Working fine for me 
![image](https://github.com/unjs/unhead/assets/5326365/e5b7c041-7354-4073-9256-0f742ce02b5f)

Can you provide a reproduction?

`useSchemaOrg` is not typed, only the define composables

**Comment by djixadin** [comment]
ill try to reproduce tomorrow..

![image](https://github.com/unjs/unhead/assets/22941532/c38ebacd-8885-4ed2-9d9f-dceeae113f02)

**Comment by djixadin** [comment]
https://stackblitz.com/edit/nuxt-starter-u8ko1u?file=app.vue,nuxt.config.ts,.nuxt%2Ftypes%2Fimports.d.ts

in the `.nuxt/types/imports.d.ts` `useSchemaOrg is of any or unknown` and it links to this file `node_modules/nuxt-schema-org/dist/runtime/nuxt/imports/useSchemaOrg.d.ts` which has this code 

```
import type { useSchemaOrg as _useSchemaOrg } from '@unhead/schema-org/vue';
type Input = Parameters<typeof _useSchemaOrg>[0];
export declare function useSchemaOrg(input: Input): any;
export {};
```
