### ISSUE TITLE
Vue Reactivity Dead Link

### ISSUE THREAD

**Issue by tripflex** [unjs/unhead#313]
### Environment

N/A

### Reproduction

https://unhead.unjs.io/setup/vue/installation scroll down to [Optional: Vue 3 Options API](https://unhead.unjs.io/setup/vue/installation#optional-vue-3-options-api)

### Describe the bug

https://unhead.unjs.io/setup/vue/reactivity

**Comment by harlan-zw** [comment]
Thanks, PRs welcome :)
