### ISSUE TITLE
Google SERP is lowering number of indexed pages on a daily basis

### ISSUE THREAD

**Issue by Dagge11** [unjs/unhead#316]
### Environment

Vue3, Vite, Nodejs, Unhead vue

### Reproduction

No

### Describe the bug

Hi
Two month ago I have launched a new Vue site implementing Unhead. It was SPA car classifieds with around 150 starting ads in the base. While at the beginning Google serp indexed quite a lot of my pages (almost 100 of total 150 ad pages) with every day it lowers number of indexed pages . In a month Google came from indexing 90 pages to 10 pages. Since nothing has changed on my site (pre-launch phase) I wonder why is this happening and is there any catch to stop this. This isn't a bug probably but have no other place to ask, thanks for understanding

**Comment by harlan-zw** [comment]
Hi, sorry but there isn't much I can do in the context of this library. Google should warn you about why your pages are not being indexed.

What I can recommend though is to use SSR, you may want to switch to using Nuxt to make your life easier.
