### ISSUE TITLE
How would I add FAQ schema dynamically?

### ISSUE THREAD

**Issue by yashwp** [unjs/unhead#317]
### Describe the change

I wanted to add multiple FAQs in the schema coming from my API. 

There is a way to add the same dynamically using components and props, but it is **not recommended** in the document itself.

I need to use `useSchemaOrg` composable and insert the `defineQuestion` dynamically, which I don't have a way of doing. 

```
useSchemaOrg([
  defineWebPage({
    '@type': currentTopic.value?.metaTitle,
  }),
  
  /// Loop over
  defineQuestion({
     name: '<question>`,
     acceptedAnswer: '<Answer>',
  })
  /// Loop ends
]);
```

### URLs

https://unhead.unjs.io/schema-org/recipes/faq

### Additional information

- [ ] Would you be willing to help?

**Comment by harlan-zw** [comment]
Not sure what you mean, you can do something like this.

```ts
useSchemaOrg([
  defineWebPage({
    '@type': currentTopic.value?.metaTitle,
  }),
  
 ...faqs.map(f => defineQuestion({ name: f.question, acceptedAnswer: f.answer }))
]);
```
