### ISSUE TITLE
Nuxt 2.15.7 / vue 2.6  - Module parse failed: Unexpected token error upon usage

### ISSUE THREAD

**Issue by tomardern** [unjs/unhead#322]
### Environment

Nuxt 2.15.7
vue: 2.6

### Reproduction

n/a

### Describe the bug

Upon usage, the below log was shown. 

### Additional context

We are currently upgrading an old vue 2 app, and want to use `unhead` to prepare us for our vue 3/nuxt 3 migration. 

Upon usage, we had a `Module parse failed: Unexpected token` error in our console/terminal.

We managed to fix this by changing our `nuxt.config.js` to ensure our babel loader was used just for unhead. See https://v2.nuxt.com/docs/features/configuration/#extend-webpack-config for more details:

```js
build: {

	extend (config) {
 	// ...
      config.module.rules.push({
        include: [
          /unhead\/.*\/index.(c|m)js$/,
        ],
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      })
      // ... etc
	}
}

```

It's taken me a while to figure this out, thought I'd share incase anyone else is having the same issue.

### Logs

```sh
ERROR  in <Project root>/node_modules/@unhead/shared/dist/index.cjs                                                                                                                                     friendly-errors 12:14:23

Module parse failed: Unexpected token (99:32)                                                                                                                                                                                        friendly-errors 12:14:23
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   options.resolveKey = options.resolveKey || ((k2) => k2);
|   const resolveKey = (index) => {
>     const arr = asArray(options?.[index]);
|     return arr.find((k2) => {
|       if (typeof k2 === "string" && k2.includes(".")) {
```
```

**Comment by harlan-zw** [comment]
Hi @tomardern, thanks for sharing your findings on this bug.

The error seems to originate from the [packrup](https://github.com/harlan-zw/packrup) dependency of Unhead. I've pushed up a fix for this syntax on the repo and it may solve this issue.

Feel free to try without the config changes with the latest version v1.8.13, although it seems likely this may still have an error elsewhere.

**Comment by tomardern** [comment]
Hi, 

I've had time to look at this again today, sadly getting the same error.
```
 ERROR  in {PROJECT}/node_modules/unhead/dist/index.mjs                                                   friendly-errors 14:07:26

Module parse failed: Unexpected token (27:29)                                                                                              friendly-errors 14:07:26
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         const dupedTag = deduping[dedupeKey];
|         if (dupedTag) {
>           let strategy = tag?.tagDuplicateStrategy;
|           if (!strategy && UsesMergeStrategy.includes(tag.tag))
|             strategy = "merge";
 ````

It's not blocking us from using unhead, as we'll just add the loader as per my first message.
