### ISSUE TITLE
`bodyAttrs` `style` does not work properly, if a style contains an URL

### ISSUE THREAD

**Issue by TheTimewaster** [unjs/unhead#325]
### Environment

@unhead/vue v1.8.13

### Reproduction

https://stackblitz.com/edit/vitejs-vite-hzfyta?file=src%2FApp.vue

### Describe the bug

When using `bodyAttrs` with `style` and the style value contains an URL, only the first part of the URL string is rendered
Usage: 
```javascript
useHead({
  bodyAttrs: {
    style: "--cover-image: url('https://example-url-to-image.com')",
    class: "body-cover"
  }
})
```

the following is rendered:
```html
<body class="body-cover" style="--cover-image: url('https;">
```

### Additional context

On further debugging, I found this line in 
https://github.com/unjs/unhead/blob/4cc95b297cb100321e622495b2618b120b12b27a/packages/dom/src/renderDOMHead.ts#L107

Once `c` contains more than one colon like for instance in an URL with the protocol, `v` only has `'https` as its value. This leads to the bug I described above.

This bug also limits the usage of `useHead` in Nuxt.

**Comment by harlan-zw** [comment]
Thank you for the detailed issue, I've pushed up a fix in v1.8.14.
