### ISSUE TITLE
vue 3.0.0 - Module parse failed: Unexpected token error 

### ISSUE THREAD

**Issue by zhenglizhao** [unjs/unhead#326]
### Environment

    "@unhead/vue": "^1.8.13",
    "vue": "^3.0.0",
    "@vue/cli-service": "^4.5.13",

### Reproduction

n/a

### Describe the bug

when use vue3 + @unhead/vue@1.8.13，the below log was shown.

### Additional context

I encountered this issue when using @ unhead/Vue in the Vue3 project. I have seen a similar issue # 322 before, but it uses Vue2 and Nuxt. I updated @ unhead/vue to 1.8.13 and configured the unhead loader according to his prompt, but it still hasn't been resolved and there are still issues. I am not sure if there is an issue with my configuration file or if there is a bug. Please tell me, thank you very much
```
    module: {
      rules: [
      {
        include: [
          /unhead\/.*\/index.(c|m)js$/,
        ],
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      }
      ]
    },
```

### Logs

```sh
in ./node_modules/@unhead/shared/dist/index.cjs

Module parse failed: Unexpected token (265:32)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   if (openGraphNamespaces.includes(fKey))
|     return "property";
>   return MetaPackingSchema[key]?.metaKey || "name";
| }
| function resolveMetaKeyValue(key) {

 error  in ./node_modules/unhead/dist/index.cjs

Module parse failed: Unexpected token (28:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         const dupedTag = deduping[dedupeKey];
|         if (dupedTag) {
|           if (!strategy && UsesMergeStrategy.includes(tag.tag))
|             strategy = "merge";
```

**Comment by harlan-zw** [comment]
This would likely be an issue with your babel config, are you setting it anywhere else besides the config you shared?

**Comment by zhenglizhao** [comment]
There are probably two more configurations, one is to use unhead in the main.js file, and the other is to use headEnable: true in the unplugin vue markdown plugin,
```
// main.js
import { createApp } from 'vue'
import App from './App.vue'

import { createHead } from '@unhead/vue'
const head = createHead();
const app = createApp(App).use(head)
// vue.config.js use unplugin-vue-markdown
 config.module
      .rule('vue')
      .test(/\.(vue|md)$/)
    config
      .plugin('markdown')
      .use(Markdown({
        headEnabled: true,
        markdownItOption: {
          html: true,
          linkify: true,
          typeography: true,
        },
        markdownItUses: [
          MarkdownItAnchor,
        ],
      }))
      .end()
```

**Comment by zhenglizhao** [comment]
Just now while doing the reproduction, I found that there was no bug left. I compared the relevant packages of Vue3 and updated them, and then they can work now
```
// old
vue: 3.0.0
@vue/cli-service: 4.5.13
@vue/cli-plugin-babel:4.5.13
// now
  "vue": "^3.2.13",
 "@vue/cli-service": "~5.0.0",
 "@vue/cli-plugin-babel": "~5.0.0",
```
Thank you for your suggestion to solve my problem. Thank you very much
