### ISSUE TITLE
html tag like "<p>" show like "u003Cp>"  in answer txt

### ISSUE THREAD

**Issue by greetfish** [unjs/unhead#329]
### Environment

node 18.19.0
nuxt 3.10.3
nuxt-schema-org 3.3.4 

### Reproduction

https://unhead.unjs.io/schema-org/schema/question

### Describe the bug
 [google structured-data](https://developers.google.com/search/docs/appearance/structured-data/faqpage#answer)  surpport HTML tags so i use in question answer,but html tag like "< p >" show like "u003Cp>" in answer txt

**Comment by harlan-zw** [comment]
This is correctly encoding the html entities within the JSON to avoid XSS. When it's parsing the characters will be decoded to HTML.

![image](https://github.com/user-attachments/assets/5105d7b0-77c5-40a4-b261-b2eb75094d94)

**Comment by greetfish** [comment]
你好，你的来信我已收到
