### ISSUE TITLE
Failed to load script in Nuxt with `useScript`

### ISSUE THREAD

**Issue by enkot** [unjs/unhead#333]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cw1ezx?file=app.vue,nuxt.config.ts

### Describe the bug

Not sure if `useScript` should work in Nuxt, but currently this code throws an error `Error: Failed to load script`:
```vue
<script lang="ts" setup>
import { useScript } from '@unhead/vue';

useScript('https://ui.powerreviews.com/stable/4.1/ui.js');
</script>
```
force use client side works fine:
```vue
<script lang="ts" setup>
import { useScript } from '@unhead/vue';

if (import.meta.client)
  useScript('https://ui.powerreviews.com/stable/4.1/ui.js');
</script>
```

**Comment by harlan-zw** [comment]
Hey @enkot, thanks for raising this issue. I just noticed this myself and pushed up a fix.

If you'd like to use `useScript` with Nuxt, you'd be better off using the `@nuxt/scripts` module. It's currently private in development, I have sent you an invite.

I'd recommend using a `trigger` or specifying client only when using `useScript` to get the most out of it in terms of performance.

**Comment by enkot** [comment]
Hey @harlan-zw, I was wondering how you fixed the bug so quickly 😄 Nice!
Wow, thanks for the invite, `@nuxt/scripts` looks great, especially the bundling and Cookie Consent.
I will try to test it thoroughly

**Comment by Botz** [comment]
@harlan-zw I also tried to use `useScript` and got an error in hydration 'Error: Missing Unhead context.' SSR works perfekt
Would it be possible to also invite me, too?
