### ISSUE TITLE
Unsafe behavior in function `normaliseStyleClassProps()`

### ISSUE THREAD

**Issue by sameignatovich** [unjs/unhead#336]
### Environment

node: v20.11.1
@unhead/shared: 1.9.4
Nuxt: 3.11.2

### Reproduction

I dunno, can't find source of problem

### Describe the bug

I'm using Nuxt which have unhead as dependency. Today was tried to upgrade Nuxt from 3.10.3 to 3.11.2 and my project won't start because of problem.

I made quick research and found what month ago function normaliseStyleClassProps() [was changed](https://github.com/unjs/unhead/commit/8e07d350dc1fc96e73019b650c781bb8a74ec105#diff-ce3d42133eb3986d8b87fd62f7eab96349c662ece7cbeed4ccd28702cd061bd9R51) and now it accept style in addition to class.

### Additional context

I change
```js
return (Array.isArray(v) ? v.join(sep) : v).split(sep).filter((c) => c.trim()).filter(Boolean).join(sep);
```
to
```js
 return (Array.isArray(v) ? v.join(sep) : v)?.split(sep).filter((c) => c.trim()).filter(Boolean).join(sep);
```
and my project works without any mistakes. I don't have any visual changes in comparison with previous version.

Can you make optional chaining fix? Is it possible or you expect this behavior (error)?

### Logs

```sh
ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'split')
  at normaliseStyleClassProps (./node_modules/.pnpm/@unhead+shared@1.9.4/node_modules/@unhead/shared/dist/index.mjs:526:47)  
  at normaliseProps (./node_modules/.pnpm/@unhead+shared@1.9.4/node_modules/@unhead/shared/dist/index.mjs:531:18)  
  at normaliseTag (./node_modules/.pnpm/@unhead+shared@1.9.4/node_modules/@unhead/shared/dist/index.mjs:493:18)  
  at ./node_modules/.pnpm/@unhead+shared@1.9.4/node_modules/@unhead/shared/dist/index.mjs:556:42  
  at Array.map (<anonymous>)  
  at ./node_modules/.pnpm/@unhead+shared@1.9.4/node_modules/@unhead/shared/dist/index.mjs:556:27  
  at Array.forEach (<anonymous>)  
  at normaliseEntryTags (./node_modules/.pnpm/@unhead+shared@1.9.4/node_modules/@unhead/shared/dist/index.mjs:554:109)  
  at Object.resolveTags (./node_modules/.pnpm/unhead@1.9.4/node_modules/unhead/dist/index.mjs:312:35)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by harlan-zw** [comment]
Hey, thanks for the issue. A reproduction would be useful but maybe it's an integration you're using causing it?

Did you want to send a PR for this? You've already done 95% of the work 😄

**Comment by sameignatovich** [comment]
Ok, after another 5 minutes of research I found the problem: I'm using optional styles in Vue composable, and it can return `undefined`. 

```js
useHead(() => ({
  htmlAttrs: {
    style: isOpen.value ? 'overflow: hidden' : undefined,
  },
}));
```

I just deleted this code and everything fine.

Optional chaining is necessary, in my opinion

**Comment by harlan-zw** [comment]
I agree, `undefined` is a valid input per the types
