### ISSUE TITLE
Allow data-* attributes with empty value or without value

### ISSUE THREAD

**Issue by Jak-Ch-ll** [unjs/unhead#348]
### Describe the feature

Currently data-* attributes that are set to `true` or `""` are rendered as `data-foo="true"`. This seems to be a deliberate decision made in #107.

## The issue

While `data-foo` and `data-foo=""` can be used interchangeably, `data-foo="true"` is not the same in all situations.

### Real world example

I stumbled onto that issue while working with the [UI5 Web Component Library](https://sap.github.io/ui5-webcomponents). Specifically we want to [customize the default font loading](https://sap.github.io/ui5-webcomponents/docs/customizing/fonts/#customizing-fonts) which requires us to add a style tag in the following form: `<style data-ui5-font-face="">`. I checked through the libraries code and they are using the following helper to check if the stylesheet exists (shortened for brevity, [full code here](https://github.com/SAP/ui5-webcomponents/blob/c542aaec7fca20cb43ca03b1b10264a8d2cd5197/packages/base/src/ManagedStyles.ts#L110)):

```ts
const hasStyle = (name: string, value = ""): boolean => {
	return !!document.querySelector(`head>style[${name}="${value}"]`);
}
```

This boils down to an attribute selector that looks like `[data-foo=""]`, which selects both `data-foo` and `data-foo=""`, but not `data-foo="true"`.

### Workaround

We are working with Nuxt, so Unhead is configured via the `nuxt.config.ts`. To keep the workaround close by, I added a script tag that replaces the `"true"` with `""`, but this feels kinda dirty, so I'm open to suggestions in that regard.
```ts
export default defineNuxtConfig({
  app: {
    head: {
      style: [{ 'data-ui5-font-face': '' }],
      script: [{
        innerHTML: 'document.querySelector("[data-ui5-font-face]").setAttribute("data-ui5-font-face", "");',
      }]
    }
  }
}]
```

### Minimal

At a minimum there should be an option to get to at least one version without the `"true"`, for example setting the empty string could result in `data-foo=""`.

### Extended

Why not give the user full control about the result. This could look something like this:

1. Boolean `{ 'data-foo': true }` results in `data-foo`
2. Empty string `{ 'data-foo': "" }` results in `data-foo=""`
3. Boolean as string `{ 'data-foo': "true" }` results in `data-foo="true"`

I feel like this is what is most congruent with user expectation (including #107) and would allow to deal with any weird behaviour of other libraries. For consistency this could even be extended to all attributes, not just `data-*`.

##  Notes

From my brief check through the code, changes should be contained witihin the [normaliseProps](https://github.com/unjs/unhead/blob/42f4cd91522cb339c2dd562b397efdd17eecb91e/packages/shared/src/normalise.ts#L65) function, so it shouldn't be too hard. But since this would be a breaking change, I think it's important to first discuss how to proceed.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hey, thanks for the detailed issue. You are right and I will try and sort this out when I have a chance. 

PRs are of course welcome I the mean time :)
