### ISSUE TITLE
Metadata will not update in production

### ISSUE THREAD

**Issue by FredericGaudreau** [unjs/unhead#353]
### Environment

"unhead": "^1.9.10",
node -v : v20.9.0

### Reproduction

installation in local is working fine and i am able to see the updated metadata. The html file already contain meta tags. 

### Describe the bug

metadata is updated successfully in local, but it will not work on production/when sharing on social media. The html file already contain meta tags. On production, only the old metadata is shown, not the updated one.

**Comment by harlan-zw** [comment]
Hi, I'll need some reproduction details if you'd like help.

**Comment by FredericGaudreau** [comment]
Hi,
the way we are using it right now. we have this code

in main page - play.domain.com/
      <meta name="description" content="description text main page">
      <meta property="og:title" content="og:title main page"/>

in the sub page using unhead - play.domain.com/subpage
    {
      name: 'description',
      content: 'description text subpage'
    },
    {
      property: 'og:title',
      content:"og:title text subpage"
    },
    
Right now, we're able to see the subpage meta data when we're on dev or in local. Unfortunetaly, on production, we only see the metadata associated with the main page when we navigate to the subpage.

**Comment by chris-visser** [comment]
This seems to be a similar issue to #294 . You can work around this by initiating createHead() with the .push method like below:

```ts
createHead().push({})
```

**Comment by harlan-zw** [comment]
I'm having issues replicating this, if anyone can provide a reproduction I'll happy look into it.
