### ISSUE TITLE
Script type doesn't include `body` property

### ISSUE THREAD

**Issue by hecktarzuli** [unjs/unhead#354]
### Environment

Nuxt 3.11.1
Node 20.12.1

### Reproduction

use the `body` property when using a script tag inside `useHead` in Nuxt 3.

### Describe the bug

It looks like useHead supports the [`body` prop of the script object](https://github.com/unjs/unhead/blob/a26255e3ee788720eb0736f1b9f862fcdf136b57/examples/nuxt3/pages/head.vue#L13), but the type for it seems to be missing.  I tried the prop and it works as expected.

![image](https://github.com/unjs/unhead/assets/2112282/9336ac2d-d257-4a83-8fea-ee1ac30dab0a)

**Comment by harlan-zw** [comment]
Hi, the reason this is still supported is for legacy support for `@vueuse/head`. It's not typed intentionally as it's ambiguous as to where in the body the tag should go.

You should follow the docs for usage: https://unhead.unjs.io/usage/guides/positions

It will no longer be functional in v2.
