### ISSUE TITLE
useScript is checking CORS and giving errors when headers are not present

### ISSUE THREAD

**Issue by juankamilo** [unjs/unhead#356]
### Environment

Nuxt 3.11.2
Unhead 1.9.12

### Reproduction

https://github.com/juankamilo/testUseScript

### Describe the bug

Hi first of all thanks for that amazing Job you are making here. 

Looks like the use Script tag is adding crossorigin="anonymous" when request for an script, doing this the CORS is evaluated.

![Screenshot 2024-06-04 at 5 37 34 PM](https://github.com/unjs/unhead/assets/1947043/16206560-001c-4148-960f-be7e98acc632)

I recreate the example in the Documentation with Google analytics and is happening and giving the usual Error: 

`"Access to script at 'https://www.google-analytics.com/analytics.js?id=UA-52983849-1' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."`

This was working before so im not sure where is the issue, I try to use Unhead 1.9.11 but this does not fixed

Not sure if is anyway to prevent this happening, acording to https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin must be avoid the tag, with this CORS is not used at all

**Comment by harlan-zw** [comment]
Hi, thank you for this issue and the reproduction.

useScript tries to optimize script loading for end-user security and privacy and such will this and the referrer-policy on to the script tag.

```ts
const instance = useScript({
  src: 'https://example.com/my-awesome-script.js',
  // setting these to false will revert the defaults
  referrerpolicy: false,
  crossorigin: false,
}, {
  use() {
    return window.myAwesomeScript
  }
})
```

Looking at your use case I'd suggest using the Nuxt Scripts Google Analytics integration, see https://scripts.nuxt.com/scripts/analytics/google-analytics

**Comment by juankamilo** [comment]
Thanks for the quick reply, I can confirm that it is working fine with these 2 parameters, the types are complaining, but it is working fine. 
I was not using analytics in this case, only following the guide to find if got same error and yes xD, but thanks
