### ISSUE TITLE
Style attribute side effect scope should not contain value

### ISSUE THREAD

**Issue by DevChanQ** [unjs/unhead#357]
### Environment

```
"@unhead/vue": "^1.9.13",
"nuxt": "^3.12.1"
```

### Reproduction

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-lkygzg?file=pages%2Findex.vue)

### Describe the bug

Currently using `useHead` to update body style attributes for different pages. It was not working for some reason, the style would be cleared no matter what.

After some investigation, I found that the styles are cleared because the tracked scope includes the value of the attribute, making the previous pending side effect unable to be removed.
https://github.com/unjs/unhead/blob/c0ca0c1cc196928b40952d525f7f5e0d9edd54ce/packages/dom/src/renderDOMHead.ts#L111-L120

My proposal is to change the scope of the side effects for style attributes to ``${ck}:${k}``, removing the value from the scope. Can confirm the bug is fixed in my patched local project.

**Comment by harlan-zw** [comment]
Hi, thank you for the detailed issue and reproduction.

A fix is available in v1.9.14.
