### ISSUE TITLE
Website crashed

### ISSUE THREAD

**Issue by typed-sigterm** [unjs/unhead#363]
### Environment

OS: Windows 11 Version 23H2 (Build 22631.3737)
UA: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0`

### Reproduction

1. https://unhead.unjs.io/
2. https://unhead.unjs.io/usage/composables/use-head-safe etc.

### Describe the bug

The first one responses:
```html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="refresh" content="0; url=https://unhead.unjs.io">
    </head>
</html>
```
This causes the page to constantly refresh.

The second one shows an 500 error:
> This Serverless Function has crashed.

**Comment by harlan-zw** [comment]
Thanks for the issue, seems to be fixed now.

**Comment by harlan-zw** [comment]
> Oops, It crashes again - [nuxt CI log](https://github.com/nuxt/nuxt/actions/runs/10370148764/job/28707414835#step:4:869)
> 
> This time it's
> 
> ![500 This page is temporarily unavailable.](https://private-user-images.githubusercontent.com/145281501/357419995-4a2b9c6e-1157-4b3c-ab82-085cb4d8d13d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTQ2MzIsIm5iZiI6MTcyMzc5NDMzMiwicGF0aCI6Ii8xNDUyODE1MDEvMzU3NDE5OTk1LTRhMmI5YzZlLTExNTctNGIzYy1hYjgyLTA4NWNiNGQ4ZDEzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNzQ1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzI3MjZmMDU5MjA1NmZmYTVhMjdmZmY2N2RmMWFiNTY1OWM4YjE4NWZlZTg5OTVlMTY0NTliYzY5YjJlODRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BPfo7IHIi4o6PY-UupVjBbFN4zTchu70QoKwBEj-jgk)

Thanks! Fixed this after like 30 attempts 😥
