### ISSUE TITLE
<head> Not showing up in markdown

### ISSUE THREAD

**Issue by vitorgouveia** [unjs/unhead#364]
### Describe the change

While investigating the project's readme I found out that the headline has a `<head>` tag in it but it's not showing up on github because it thinks it's html

I didn't want have to fork the repository so here's the solution
```md
Universal document &lt;head&gt; tag manager. Tiny, adaptable and full featured.
``` 

### Additional information

- [X] Would you be willing to help?

**Comment by harlan-zw** [comment]
Thanks :)
