### ISSUE TITLE
Cannot find module '@unhead/vue/components' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by rezelute** [unjs/unhead#366]
### Environment

node --version = v20.14.0
@unhead/vue": "^1.7.4"

### Reproduction

![image](https://github.com/unjs/unhead/assets/13378850/e61949ee-43c9-424e-855b-755feeed5343)

### Describe the bug

According to the [Docs](https://unhead.unjs.io/setup/vue/components), this should work in Vue:
`import { Head } from '@unhead/vue/components'`

But I am getting the ts error: Cannot find module '@unhead/vue/components' or its corresponding type declarations.ts(2307).

This is what I have in my node_modules:
![image](https://github.com/unjs/unhead/assets/13378850/b03d3c67-7193-4108-ba5a-cd00658e7283)

**Comment by harlan-zw** [comment]
Could you please try the latest version?

**Comment by harlan-zw** [comment]
I think this may have been fixed with one of the Unbuild version updates.

![image](https://github.com/user-attachments/assets/671b78d5-4477-4697-a18c-a4758a9153ec)
