### ISSUE TITLE
Schema.org Video Tag Invalid

### ISSUE THREAD

**Issue by KyleSmith0905** [unjs/unhead#369]
### Environment

Node - v18.19.1
NPM - v10.2.4
Schema.org - v1.9.16

### Reproduction

https://github.com/KyleSmith0905/mre--schema-org-video/blob/main/app.vue

You will find a schema.org object like:
```json
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@id": "http://localhost:3000/#website",
      "@type": "WebSite",
      "name": "nuxt-app",
      "url": "http://localhost:3000/"
    },
    {
      "@id": "http://localhost:3000/#webpage",
      "@type": "WebPage",
      "name": "Welcome to Nuxt!",
      "url": "http://localhost:3000/",
      "isPartOf": {
        "@id": "http://localhost:3000/#website"
      },
      "potentialAction": [
        {
          "@type": "ReadAction",
          "target": [
            "http://localhost:3000/"
          ]
        }
      ]
    },
    {
      "@id": "http://localhost:3000/#/schema/video/e09e196",
      "@type": "VideoObject",
      "description": "Description of video",
      "name": "Title of video",
      "uploadDate": "[object Object]",
      "url": "https://yskkyle.com",
      "thumbnailUrl": {
        "@type": "ImageObject",
        "url": "https://yskkyle.com/icons/logo192.png",
        "contentUrl": "https://yskkyle.com/icons/logo192.png"
      }
    }
  ]
}
```

Enter that into: https://validator.schema.org/

### Describe the bug

My video pages are getting errors when google is indexing those pages.

I entered my schema into Google's schema validator and it seems like thumbnailUrl is just a string, and not a imageObject?

### Additional context

Didn't work on my Angular project (In which I was using @unhead/schema-org directly) or my Nuxt reproduction.

**Comment by harlan-zw** [comment]
Fixed with https://github.com/unjs/unhead/pull/391 merge
