### ISSUE TITLE
To be precise, I cannot find an example that runs on version 2.6.14 of Vue.

### ISSUE THREAD

**Issue by mdxiaohu** [unjs/unhead#374]
### Environment

16

### Reproduction

I saw examples in the official library that Vue is using version 2.7.

### Describe the bug

In version 2.6.14, many exports are not available.
This will result in an error message.
for example:
[ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "version"
ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "unref"
...

Can you change the 2.7 version in the official example to 2.6 and try again to see if it runs correctly.
I am using Vite4+Vue 2.6.14.
Can I directly use the unhead library? Or is it necessary to use the corresponding Vue version?

**Comment by harlan-zw** [comment]
Sorry but Vue 2.6 is not supported. I'd suggest using https://vue-meta.nuxtjs.org/
