### ISSUE TITLE
How to get meta information in the synchronization method

### ISSUE THREAD

**Issue by AllenIverson1122** [unjs/unhead#380]
### Describe the feature

The renderSSRHead method is an asynchronous execution method. If synchronous acquisition is required, how to define it?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hi, this is not possible in v1 as we allow users to provide promises as input to `useHead`. This behavior is under consideration of being dropped for the v2.

**Comment by harlan-zw** [comment]
I'll investigate support for this in v2, have added to the [roadmap](https://github.com/unjs/unhead/issues/395).
