### ISSUE TITLE
Article: datePublished does not support date object as value

### ISSUE THREAD

**Issue by felixranesberger** [unjs/unhead#384]
### Describe the change

The documentation shows at multiple places that you can provide JS date objects instead of literal strings to schemas. I could only get it to work, by providing the date as a string. 

```
"dateModified": "[object Object]", => provided date object
"datePublished": "2021-01-01", => provided string
```

(I already created a pull request fixing another issue with wrong date creation, before knowing that it doesn't work at all)

### URLs

https://unhead.unjs.io/schema-org/recipes/blog#marking-up-an-article
https://unhead.unjs.io/schema-org/schema/article#resolves

### Additional information

- [X] Would you be willing to help?

**Comment by felixranesberger** [comment]
Hi Harlan, I think this is still an issue. 
In a short summary: when I provide a `date object` to `dateModified` or `datePublished` as stated in the documentation, it doesn't output the correct date iso string. 

I currently use `lastModifiedDate.toISOString()` to fix this, but users who don't check the schema output and just follow the documentation may run into issues further down the road.

This is my full (working) code:
```vue
useSchemaOrg([
  defineArticle({
    headline: props.title,
    description: props.description,
    datePublished: props.publishDate.toISOString(),
    dateModified: props.lastModifiedDate.toISOString(),
    image: props.imageUrl,
    author: {
      name: props.author.fullName,
      url: props.author.url,
    },
    keywords: props.keywords,
    inLanguage: 'en',
  }),
])
```

**Comment by harlan-zw** [comment]
Oops sorry, let me re-open
