### ISSUE TITLE
Add warning when there is double/conflict of head tags

### ISSUE THREAD

**Issue by moshetanzer** [unjs/unhead#385]
### Describe the feature

Hey,

In big Nuxt pages often we have come across that meta tags have been declared twice for the page:
- when there are simply two head or seometa tags
- when there is a overriding tag in nuxt or app config
- when there is an overriding tag in app.vue

it would be great dx and for seo to give a console warning on build/dev of any tags that have already declared for that route/page.

Regards

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hey, thanks for the suggestion :slightly_smiling_face: .

I may consider this for https://github.com/unjs/unhead/issues/394, will track there.
