### ISSUE TITLE
JSON in <script> attributes is HTML escaped

### ISSUE THREAD

**Issue by paolieri** [unjs/unhead#404]
### Environment

Node.js v22.9.0
Nuxt 3.13.2 
Nitro 2.9.7                                                                                                                                                                                          
Unhead 1.11.6

### Reproduction

In the default template, add:

```
<script setup lang="ts">
useHead({
  script: [{
    tagPosition: 'bodyClose',
    defer: true,
    src: 'https://static.cloudflareinsights.com/beacon.min.js',
    'data-cf-beacon': '{"token": "mytoken"}'
  }]
})
</script>
```

### Describe the bug

The resulting HTML is:

```
...<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;token&quot;: &quot;mytoken&quot;}"></script></body>
```

### Additional context

Cloudflare Web Analytics suggests adding:

```
<script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "mytoken"}'></script>
```

before the ending body tag.

The problem is that `data-cf-beacon` contains valid JSON (with double quotes); if I use `useHead` for this, the JSON gets HTML escaped.

Is there any way to obtain attributes with single quotes and without HTML escaped content?

**Comment by harlan-zw** [comment]
There isn't an easy solution for the encoding.

I'd suggest just using the query params instead `https://static.cloudflareinsights.com/beacon.min.js?token=$SITE_TOKEN&spa=true` or only register it on the client 

```ts
useHead({
  script: [{
    tagPosition: 'bodyClose',
    defer: true,
    src: 'https://static.cloudflareinsights.com/beacon.min.js',
    'data-cf-beacon': '{"token": "mytoken"}'
  }]
}, {
  mode: 'client',
})
```

As you're using Nuxt I'd suggest https://scripts.nuxt.com/scripts/analytics/cloudflare-web-analytics

**Comment by paolieri** [comment]
This works, thanks!
