### ISSUE TITLE
DEP0155 warnings in schema-org when building on Windows

### ISSUE THREAD

**Issue by Ingramz** [unjs/unhead#405]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

```
npx nuxi init
cd nuxt-app
npx nuxi@latest module add schema-org
npm run build
````

### Describe the bug

https://github.com/unjs/unhead/commit/1cea6c46cdc61f57cc5776d6c2f0a7a8a3dcd570 introduced build warnings on Windows when building for production.

```
(node:21972) [DEP0155] DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field module resolution of the package at D:\random\nuxt-app\node_modules\@unhead\schema-org\package.json imported from D:\random\nuxt-app\node_modules. Mapping specifiers ending in "/" is no longer supported.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Since they are just warnings, the build will succeed, however in larger projects the amount of warnings emitted is rather obnoxious and makes them hard to ignore.

Edit: it seems like there is a relevant issue raised at nitro https://github.com/unjs/nitro/issues/2523 . With `unjs/mlly` which was updated just an hour ago, the amount of warnings was significantly reduced, but I guess it remains to be seen what can be done about the DEP0155 warning. Perhaps this is not an issue that needs to be fixed at schema-org after all...

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. I have removed this export as I only introduced it trying to debug the `/vue` export path types which I found a solution for.
