### ISSUE TITLE
Tag 1.1.11 is not available for some unhead packages

### ISSUE THREAD

**Issue by lermontex** [unjs/unhead#413]
### Environment

...

### Reproduction

https://www.npmjs.com/package/@unhead/addons/v/1.11.11 - 200
https://www.npmjs.com/package/@unhead/dom/v/1.11.11 - 200
https://www.npmjs.com/package/@unhead/schema-org/v/1.11.11 - 404
https://www.npmjs.com/package/@unhead/schema/v/1.11.11 - 200
https://www.npmjs.com/package/@unhead/shared/v/1.11.11 - 200
https://www.npmjs.com/package/@unhead/ssr/v/1.11.11 - 404
https://www.npmjs.com/package/@unhead/vue/v/1.11.11 - 404
...

### Describe the bug

Tag 1.1.11 is not available for some unhead packages (npmjs.com). It seems it shouldn't be like that

**Comment by harlan-zw** [comment]
Hey, thanks for raising this. I think my internet cut out while it was deploying. It should be fixed now.
