### ISSUE TITLE
Server does not load tags in SSR

### ISSUE THREAD

**Issue by evanqhu** [unjs/unhead#422]
### Environment

Node: v18.18.2
Vue: v3.5.13
@unhead/vue: v1.11.13
@unhead/ssr: v1.11.13

### Reproduction

https://stackblitz.com/~/github.com/evanqhu/unhead-ssr-demo

### Describe the bug

I used useHead to add title and meta in App.vue. I expected that in SSR, the html file returned by the server would contain the title and meta I added, but the actual html file returned did not, they were added in the client.

(Each attribute of payload printed in src/entry-server.ts is an empty string, and I expect it to contain the title and meta information I added.)

I don't know if I used useHead the right way in SSR. Hope to get some help. Thank you !

**Comment by harlan-zw** [comment]
The issue with your rendering the SSR head _before_ Vue has rendered, so there's no way for the tags to be generated at this stage.

Simply move it around and it will work

```ts

export async function render(_url: string) {
  const { app, head } = createApp()

  await head.resolveTags()
  
  const ctx = {}
  const html = await renderToString(app, ctx)

  const payload = await renderSSRHead(head)
  console.log("🚀🚀🚀 payload", payload);

  return { html, payload }
}
```

**Comment by evanqhu** [comment]
Oh, it works, thanks a lot! 🥹
