### ISSUE TITLE
Cannot use computed getter

### ISSUE THREAD

**Issue by itsTPM** [unjs/unhead#430]
### Environment

Node.js v22.12.0, unhead 1.11.14, vue 3.5.13, vite 6.0.5

### Reproduction

Basic example from [documentation](https://unhead.unjs.io/setup/vue/how-it-works):
```
<script setup>
import { ref } from "vue";
import { useHead } from "unhead";

const myPage = ref({ description: "This is my page" });

useHead({
  meta: [{ name: "description", content: () => myPage.value.description }],
});
</script>
```

### Describe the bug

When I try to use the computed getter following the example from the documentation, in HTML I only get `<meta name="description" content="() => myPage.value.description">`, just function converted to string

I tried using IIFE, and in output I get valid content for meta tag, but it's not updating when my ref changes. Cannot figure out how to use computed getter correctly with this library

**Comment by harlan-zw** [comment]
If you're using Vue you need to import from `@unhead/vue`. I'll try and make this clearer in the docs next time I have a chance

**Comment by itsTPM** [comment]
It works now, thanks! I accidentally missed that the documentation has its own installation instructions for Vue, my bad
