### ISSUE TITLE
unheadVueComposablesImports ts error

### ISSUE THREAD

**Issue by productdevbook** [unjs/unhead#64]
### Environment

ts 4.9
node 18

### Reproduction

![image](https://user-images.githubusercontent.com/38668796/210095153-be41e4be-b5e5-485d-97a0-d00abf508c30.png)

### Describe the bug

When I add it, it gives ts error like on the screen

**Comment by harlan-zw** [comment]
Hey @productdevbook, thanks for the issue.

Looks like it was using a format for an earlier version of `unplugin-auto-import`. I've pushed up a fix to use the new format, it's available in 1.0.15.
