### ISSUE TITLE
Set up general `titleTemplate` when using `createHead`

### ISSUE THREAD

**Issue by jippy89** [unjs/unhead#91]
### Describe the feature

Hi, I was wondering on how to do this.

What I imagine was that it will be used across "page" component, and we will set it only once when we registered the plugin to Vue. Is there such feature? I don't know if this is common or not.

I've read the docs of [Title Template](https://unhead.harlanzw.com/guide/guides/title-template), but all I see is how to configure it in the "page" component. Not the overall component.

If it turns out there's already a feature of it, please refer me to the docs. Thank you!

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by harlan-zw** [comment]
Hey @jippy89, thanks for the issue :)

Would you mind sharing some details about your implementation?

Most implementations will have two opportunities for setting root meta.

1. While creating the head

This is code straight from nuxt, where appHead could be `{ app: { head: { titleTemplate: '%s - my site' } }`

```
  const head = createHead()
  head.push(appHead)
```

2. Within the root vue component (App.vue usually)

```ts
useHead({
  titleTemplate: '%s - my site'
})
```

**Comment by harlan-zw** [comment]
Going to close, feel free to open if the above doesn't help.

**Comment by jippy89** [comment]
I just want to say thanks @harlan-zw for the answer. Apparently my project seem to use Vue 2 instead of Vue 3. So I'm using another packages and did not follow up this issue.

**Comment by harlan-zw** [comment]
No problem :) Vue 2 is [supported](https://unhead.harlanzw.com/integrations/vue/setup#vue-2) but understand if using another package is easier.
